/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MantReclPrv.java
 *
 * Created on 18-mar-2011, 13:24:34
 */

package gnu.chu.anjelica.compras;

import java.sql.Types;
import java.util.ArrayList;
import java.util.Vector;

/**
 *
 * @author jpuente
 */
public class MantReclPrv extends javax.swing.JInternalFrame {

    /** Creates new form MantReclPrv */
    public MantReclPrv() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        apr_estrecE = new gnu.chu.controles.CComboBox();
        apr_kilosE = new gnu.chu.controles.CTextField(Types.DECIMAL,"---,--9.99");
        apr_precioE = new gnu.chu.controles.CTextField(Types.DECIMAL,"--,--9.99");
        apr_implinE = new gnu.chu.controles.CTextField(Types.DECIMAL,"----,--9.99");
        apr_comentE = new gnu.chu.controles.CTextField(Types.CHAR,"X",40);
        Pprinc = new gnu.chu.controles.CPanel();
        cLabel11 = new gnu.chu.controles.CLabel();
        jtRec = new gnu.chu.controles.CGridEditable(5);

        apr_estrecE.addItem("Pendiente", "P");
        apr_estrecE.addItem("Aceptado", "A");
        apr_estrecE.addItem("Rechazado", "R");
        apr_estrecE.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        apr_implinE.setEnabled(false);

        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        Pprinc.setLayout(null);

        cLabel11.setText("Reclamaciones");
        Pprinc.add(cLabel11);
        cLabel11.setBounds(70, 10, 160, 15);

        {
            Vector v=new Vector();
            v.add("Estado"); // 0 Estado
            v.add("Kilos"); // 1 Kilos
            v.add("Precio"); // 2 Precio
            v.add("Importe"); // 3 Imp. Linea
            v.add("Comentario"); // 4
            jtRec.setCabecera(v);
            ArrayList vc=new ArrayList();

            vc.add(apr_estrecE);
            vc.add(apr_kilosE);
            vc.add(apr_precioE);
            vc.add(apr_implinE);
            vc.add(apr_comentE);
            try{
                jtRec.setCampos(vc);
            } catch (Exception k) {}
        }
        jtRec.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jtRecLayout = new javax.swing.GroupLayout(jtRec);
        jtRec.setLayout(jtRecLayout);
        jtRecLayout.setHorizontalGroup(
            jtRecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 608, Short.MAX_VALUE)
        );
        jtRecLayout.setVerticalGroup(
            jtRecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );

        Pprinc.add(jtRec);
        jtRec.setBounds(0, 30, 610, 100);

        getContentPane().add(Pprinc);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gnu.chu.controles.CPanel Pprinc;
    private gnu.chu.controles.CTextField apr_comentE;
    private gnu.chu.controles.CComboBox apr_estrecE;
    private gnu.chu.controles.CTextField apr_implinE;
    private gnu.chu.controles.CTextField apr_kilosE;
    private gnu.chu.controles.CTextField apr_precioE;
    private gnu.chu.controles.CLabel cLabel11;
    private gnu.chu.controles.CGridEditable jtRec;
    // End of variables declaration//GEN-END:variables

}
