/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MantReclPrv.java
 *
 * Created on 18-mar-2011, 13:24:34
 */

package gnu.chu.anjelica.compras;

import gnu.chu.Menu.Principal;
import gnu.chu.anjelica.pad.MantPaises;
import gnu.chu.anjelica.pad.pdempresa;
import gnu.chu.controles.StatusBar;
import gnu.chu.interfaces.PAD;
import gnu.chu.utilidades.EntornoUsuario;
import gnu.chu.utilidades.navegador;
import gnu.chu.utilidades.ventanaPad;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.sql.Types;
import java.util.ArrayList;
import java.util.Hashtable;
import java.util.Vector;

/**
 *
 * @author jpuente
 */
public class MantReclPrv extends ventanaPad implements PAD
{
  boolean ARG_MODCONSULTA=false;
  public MantReclPrv(EntornoUsuario eu, Principal p)
  {
    this(eu,p,null);
  }

  public MantReclPrv(EntornoUsuario eu, Principal p, Hashtable ht)
  {
      EU = eu;
      vl = p.panel1;
      jf = p;
      eje = true;     

      try
      {
        ponParametros(ht);

        if (jf.gestor.apuntar(this))
          jbInit();
        else
          setErrorInit(true);
      }
      catch (Exception e)
      {
        ErrorInit(e);
      }
    }
    public MantReclPrv(gnu.chu.anjelica.menu p, EntornoUsuario eu)
    {
        this(p,eu,null);
    }
    
    public MantReclPrv(gnu.chu.anjelica.menu p, EntornoUsuario eu,Hashtable ht)
    {
      EU = eu;
      vl = p.getLayeredPane();
      
      eje = false;
      ponParametros(ht);
      try
      {
        jbInit();
      }
      catch (Exception e)
      {
        ErrorInit(e);
      }
    }
    
    
     
    
    private void ponParametros(Hashtable ht)
    {
         setTitulo("Mant. Reclamación Proveedores"); 
    }
    private void jbInit() throws Exception
    { 
      this.setVersion("2016-05-23" + (ARG_MODCONSULTA ? " SOLO LECTURA" : ""));
      statusBar = new StatusBar(this);
      nav = new navegador(this,dtCons,false);
      iniciarFrame();
      strSql = "SELECT tar_fecini,tar_fecfin,tar_codi FROM tarifa"+
          " group by tar_fecini,tar_fecfin,tar_codi" +
          " order by tar_fecini,tar_codi";
      this.getContentPane().add(nav, BorderLayout.NORTH);
      this.getContentPane().add(statusBar, BorderLayout.SOUTH);
      this.setPad(this);
      navActivarAll();
      dtCons.setLanzaDBCambio(false);
      initComponents();
      iniciarBotones(Baceptar, Bcancelar);
      this.setSize(new Dimension(582,522));
      conecta();
      activar(false);
      if (ARG_MODCONSULTA)
      {
        nav.removeBoton(navegador.ADDNEW);
        nav.removeBoton(navegador.EDIT);
        nav.removeBoton(navegador.DELETE);
      }
//      statusBar.add(Bimpri, new GridBagConstraints(9, 0, 1, 2, 0.0, 0.0
//                            , GridBagConstraints.EAST,
//                            GridBagConstraints.VERTICAL,
//                            new Insets(0, 5, 0, 0), 0, 0));

    }
    @Override
    public void iniciarVentana() throws Exception
    {
     
      activarEventos();
      activar(false);
      acc_idE.iniciar(dtStat,this,vl,EU);
//      verDatos();p
      nav.requestFocus();
      Pprinc.setDefButton(Baceptar);
//      Pprinc.setEscButton(Bcancelar);
    }

    void activarEventos()
    {
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        apr_estrecE = new gnu.chu.controles.CComboBox();
        apr_kilosE = new gnu.chu.controles.CTextField(Types.DECIMAL,"---,--9.99");
        apr_precioE = new gnu.chu.controles.CTextField(Types.DECIMAL,"--,--9.99");
        apr_implinE = new gnu.chu.controles.CTextField(Types.DECIMAL,"----,--9.99");
        apr_comentE = new gnu.chu.controles.CTextField(Types.CHAR,"X",40);
        Pprinc = new gnu.chu.controles.CPanel();
        Pcabe = new gnu.chu.controles.CPanel();
        cLabel1 = new gnu.chu.controles.CLabel();
        rpv_codiE = new gnu.chu.controles.CTextField(Types.DECIMAL,"#,###,##9");
        cLabel2 = new gnu.chu.controles.CLabel();
        acc_idE = new gnu.chu.camposdb.AccPanel();
        cLabel3 = new gnu.chu.controles.CLabel();
        par_codiE = new gnu.chu.controles.CTextField(Types.DECIMAL,"#,###,##9");
        pal_codiE = new gnu.chu.controles.CTextField(Types.DECIMAL,"##9");
        jtRec = new gnu.chu.controles.CGridEditable(5);

        apr_estrecE.addItem("Pendiente", "P");
        apr_estrecE.addItem("Aceptado", "A");
        apr_estrecE.addItem("Rechazado", "R");
        apr_estrecE.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        apr_implinE.setEnabled(false);

        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        Pprinc.setLayout(null);

        Pcabe.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        Pcabe.setLayout(null);

        cLabel1.setText("Incidencia");
        Pcabe.add(cLabel1);
        cLabel1.setBounds(360, 10, 70, 15);
        Pcabe.add(rpv_codiE);
        rpv_codiE.setBounds(130, 10, 60, 17);

        cLabel2.setText("Codigo Reclamación ");
        Pcabe.add(cLabel2);
        cLabel2.setBounds(10, 10, 120, 15);
        Pcabe.add(acc_idE);
        acc_idE.setBounds(250, 10, 110, 18);

        cLabel3.setText("Albaran");
        Pcabe.add(cLabel3);
        cLabel3.setBounds(200, 10, 50, 15);
        Pcabe.add(par_codiE);
        par_codiE.setBounds(420, 10, 60, 17);
        Pcabe.add(pal_codiE);
        pal_codiE.setBounds(482, 10, 30, 17);

        Pprinc.add(Pcabe);
        Pcabe.setBounds(10, 0, 610, 70);

        {
            Vector v=new Vector();
            v.add("Estado"); // 0 Estado
            v.add("Kilos"); // 1 Kilos
            v.add("Precio"); // 2 Precio
            v.add("Importe"); // 3 Imp. Linea
            v.add("Comentario"); // 4
            jtRec.setCabecera(v);
            ArrayList vc=new ArrayList();

            vc.add(apr_estrecE);
            vc.add(apr_kilosE);
            vc.add(apr_precioE);
            vc.add(apr_implinE);
            vc.add(apr_comentE);
            try{
                jtRec.setCampos(vc);
            } catch (Exception k) {}
        }
        jtRec.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jtRecLayout = new javax.swing.GroupLayout(jtRec);
        jtRec.setLayout(jtRecLayout);
        jtRecLayout.setHorizontalGroup(
            jtRecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 608, Short.MAX_VALUE)
        );
        jtRecLayout.setVerticalGroup(
            jtRecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );

        Pprinc.add(jtRec);
        jtRec.setBounds(20, 160, 610, 100);

        getContentPane().add(Pprinc);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gnu.chu.controles.CPanel Pcabe;
    private gnu.chu.controles.CPanel Pprinc;
    private gnu.chu.camposdb.AccPanel acc_idE;
    private gnu.chu.controles.CTextField apr_comentE;
    private gnu.chu.controles.CComboBox apr_estrecE;
    private gnu.chu.controles.CTextField apr_implinE;
    private gnu.chu.controles.CTextField apr_kilosE;
    private gnu.chu.controles.CTextField apr_precioE;
    private gnu.chu.controles.CLabel cLabel1;
    private gnu.chu.controles.CLabel cLabel2;
    private gnu.chu.controles.CLabel cLabel3;
    private gnu.chu.controles.CGridEditable jtRec;
    private gnu.chu.controles.CTextField pal_codiE;
    private gnu.chu.controles.CTextField par_codiE;
    private gnu.chu.controles.CTextField rpv_codiE;
    // End of variables declaration//GEN-END:variables

    @Override
    public void PADPrimero() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void PADAnterior() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void PADSiguiente() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void PADUltimo() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void ej_query1() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void canc_query() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void ej_edit1() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void canc_edit() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void ej_addnew1() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void canc_addnew() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void ej_delete1() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void canc_delete() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void activar(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
