package gnu.chu.anjelica.despiece;

/**
 *
 * <p>Título: DatosTrazaGrid </p>
 * <p>Descripción: Ventana con un grid que en conjuncion con listraza muestra y
 * permite modificar una hoja de trazabilidad.
 *  </p>
 *  <p>Copyright: Copyright (c) 2005-2017
 *  Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo
 *  los terminos de la Licencia Pública General de GNU según es publicada por
 *  la Free Software Foundation, bien de la versión 2 de dicha Licencia
 *  o bien (según su elección) de cualquier versión posterior.
 *  Este programa se distribuye con la esperanza de que sea útil,ed
 *  pero SIN NINGUNA GARANTIA, incluso sin la garantía MERCANTIL implícita
 *  o sin garantizar la CONVENIENCIA PARA UN PROPOSITO PARTICULAR.
 *  Véase la Licencia Pública General de GNU para más detalles.
 *  Debería haber recibido una copia de la Licencia Pública General junto con este programa.
 *  Si no ha sido así, escriba a la Free Software Foundation, Inc.,
 *  en 675 Mass Ave, Cambridge, MA 02139, EEUU.
 * </p>
 * @author ChuchiP
 * @version 1.0
 */

import gnu.chu.anjelica.compras.MantAlbComCarne;
import gnu.chu.anjelica.despiece.listraza.DatosTraza;
import gnu.chu.controles.CGridEditable;
import gnu.chu.controles.StatusBar;
import gnu.chu.utilidades.EntornoUsuario;
import gnu.chu.utilidades.SystemOut;
import gnu.chu.utilidades.ventana;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Types;
import java.util.ArrayList;
import java.util.Vector;

public class DatosTrazaGrid extends ventana {
    int MINLONCROTAL=MantAlbComCarne.MINLONCROTAL;
    private final int JT_NUMCRO=4;
    private boolean cambioCrotal=false;
  
    public DatosTrazaGrid(EntornoUsuario eu)
    {
        EU=eu;
        this.setTitulo("Datos Trazabilidad");
        this.setResizable(true);
        this.setClosable(false);
        this.setIconifiable(false);
        MINLONCROTAL=EU.getValorParam("minLonCrotal", MINLONCROTAL);
        statusBar = new StatusBar(this);
        initComponents();
        this.setSize(new Dimension(740, 481));
        this.getContentPane().add(statusBar, BorderLayout.SOUTH);
    }
    
    public void iniciarVentana(ArrayList datos )
    {   
        jt.panelBusqueda.setVisible(false);
        jt.setEnabled(false);
        jt.removeAllDatos();
        int nRow=datos.size();
        for (int n=0;n<nRow;n++)
            jt.addLinea( ((DatosTraza) datos.get(n)).getVector());
        jt.setEnabled(true);
        jt.requestFocusInicio();
        pro_loteE.addKeyListener(new KeyAdapter()
        {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode()==KeyEvent.VK_F3)
                {
                    pro_loteE.setText(MantAlbComCarne.getRandomCrotal(pro_loteE.getText(),MINLONCROTAL));
                    cambioCrotal=true;
                }
            }
        });
    }
    
   
    CGridEditable getGrid()
    {
        return jt;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pro_codiE = new gnu.chu.controles.CTextField(Types.DECIMAL,"####9");
        pro_nombE = new gnu.chu.controles.CTextField(Types.CHAR,"X",40);
        pro_etiquE = new gnu.chu.controles.CTextField(Types.CHAR,"X",40);
        acl_kilosE = new gnu.chu.controles.CTextField(Types.DECIMAL,"--,--9.99");
        pro_loteE = new gnu.chu.controles.CTextField(Types.CHAR,"X",40);
        mataderoE = new gnu.chu.controles.CTextField(Types.CHAR,"X",40);
        saladespE = new gnu.chu.controles.CTextField(Types.CHAR,"X",40);
        nacimientoE = new gnu.chu.controles.CTextField(Types.CHAR,"X",40);
        engordeE = new gnu.chu.controles.CTextField(Types.CHAR,"X",40);
        artorigenE = new gnu.chu.controles.CTextField(Types.CHAR,"X",40);
        fecsacrE = new gnu.chu.controles.CTextField(Types.DATE,"dd-MM-yy");
        comentE = new gnu.chu.controles.CTextField(Types.CHAR,"X",40);
        fecCaduE = new gnu.chu.controles.CTextField(Types.DATE,"dd-MM-yy");
        jt = new gnu.chu.controles.CGridEditable(13);
        BregCrotal = new gnu.chu.controles.CButton();

        pro_codiE.setEnabled(false);

        pro_nombE.setEnabled(false);

        pro_etiquE.setEnabled(false);

        acl_kilosE.setEnabled(false);

        comentE.setEnabled(false);

        Vector v=new Vector();
        v.add("Codigo"); //0
        v.add("Nombre"); // 1
        v.add("Indiv"); // 2
        v.add("Kilos"); // 3
        v.add("NºCrotal"); // 4
        v.add("Matadero"); // 5
        v.add("Sala Desp."); // 6
        v.add("Nacimiento"); // 7
        v.add("Engorde"); // 8
        v.add("Art.Origen"); // 9
        v.add("F.Sacrificio"); //10
        v.add("Comentarios"); // 11
        v.add("F.Cad"); //12
        jt.setCabecera(v);
        try {
            ArrayList v1=new ArrayList();
            v1.add(pro_codiE);
            v1.add(pro_nombE);
            v1.add(pro_etiquE);
            v1.add(acl_kilosE);
            v1.add(pro_loteE);
            v1.add(mataderoE);
            v1.add(saladespE);
            v1.add(nacimientoE);
            v1.add(engordeE);
            v1.add(artorigenE);
            v1.add(fecsacrE);
            v1.add(comentE);
            v1.add(fecCaduE);
            jt.setCampos(v1);
        } catch (Exception k) {SystemOut.print(k);}
        jt.setAlinearColumna(new int[]{2,0,0,2,0,0,0,0,0,0,1,0,1});
        jt.setAnchoColumna(new int[]{50,150,80,50,150,120,120,120,120,140,70,120,70});

        jt.setFormatoColumna(10,"dd-MM-yy");
        jt.setFormatoColumna(12,"dd-MM-yy");
        jt.setCanDeleteLinea(false);
        jt.setCanInsertLinea(false);

        javax.swing.GroupLayout jtLayout = new javax.swing.GroupLayout(jt);
        jt.setLayout(jtLayout);
        jtLayout.setHorizontalGroup(
            jtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 543, Short.MAX_VALUE)
        );
        jtLayout.setVerticalGroup(
            jtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 294, Short.MAX_VALUE)
        );

        getContentPane().add(jt, java.awt.BorderLayout.CENTER);

        BregCrotal.setText("Regenerar Crotales");
        BregCrotal.setMaximumSize(new java.awt.Dimension(120, 20));
        BregCrotal.setMinimumSize(new java.awt.Dimension(120, 20));
        BregCrotal.setPreferredSize(new java.awt.Dimension(120, 20));
        BregCrotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BregCrotalActionPerformed(evt);
            }
        });
        getContentPane().add(BregCrotal, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BregCrotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BregCrotalActionPerformed
        for (int n=0;n<jt.getRowCount();n++)
        {
            int swRep=0;
            for (int n1=n+1;n1<jt.getRowCount();n1++)
            {
                if (jt.getValString(n,JT_NUMCRO).equals(jt.getValString(n1,JT_NUMCRO)))
                    swRep++;
                if (swRep>1)
                    break;
            }
            if (swRep>1)
            {
                jt.setValor(MantAlbComCarne.getRandomCrotal(jt.getValString(n,JT_NUMCRO),MINLONCROTAL),n,JT_NUMCRO);
                cambioCrotal=true;
            }
        }
    }//GEN-LAST:event_BregCrotalActionPerformed
    public boolean isCambioCrotal()
    {
        return cambioCrotal;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gnu.chu.controles.CButton BregCrotal;
    private gnu.chu.controles.CTextField acl_kilosE;
    private gnu.chu.controles.CTextField artorigenE;
    private gnu.chu.controles.CTextField comentE;
    private gnu.chu.controles.CTextField engordeE;
    private gnu.chu.controles.CTextField fecCaduE;
    private gnu.chu.controles.CTextField fecsacrE;
    private gnu.chu.controles.CGridEditable jt;
    private gnu.chu.controles.CTextField mataderoE;
    private gnu.chu.controles.CTextField nacimientoE;
    private gnu.chu.controles.CTextField pro_codiE;
    private gnu.chu.controles.CTextField pro_etiquE;
    private gnu.chu.controles.CTextField pro_loteE;
    private gnu.chu.controles.CTextField pro_nombE;
    private gnu.chu.controles.CTextField saladespE;
    // End of variables declaration//GEN-END:variables

}
