/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gnu.chu.anjelica.despiece;

/**
 *
 * @author cpuente
 */
public class ManPreValDesp extends javax.swing.JInternalFrame
{

    /**
     * Creates new form ManPreValDesp
     */
    public ManPreValDesp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pprinc = new gnu.chu.controles.CPanel();
        Pcabe = new gnu.chu.controles.CPanel();
        cLabel1 = new gnu.chu.controles.CLabel();
        tid_codiE = new gnu.chu.camposdb.tidCodi2();
        cLabel2 = new gnu.chu.controles.CLabel();
        proPanel1 = new gnu.chu.camposdb.proPanel();

        Pprinc.setLayout(null);

        Pcabe.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Pcabe.setLayout(null);

        cLabel1.setText("Producto");
        Pcabe.add(cLabel1);
        cLabel1.setBounds(10, 24, 70, 17);

        tid_codiE.setAncTexto(40);
        Pcabe.add(tid_codiE);
        tid_codiE.setBounds(90, 2, 250, 18);

        cLabel2.setText("Tipo Despiece ");
        Pcabe.add(cLabel2);
        cLabel2.setBounds(2, 2, 81, 17);
        Pcabe.add(proPanel1);
        proPanel1.setBounds(70, 24, 310, 18);

        Pprinc.add(Pcabe);
        Pcabe.setBounds(0, 0, 390, 80);

        getContentPane().add(Pprinc, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gnu.chu.controles.CPanel Pcabe;
    private gnu.chu.controles.CPanel Pprinc;
    private gnu.chu.controles.CLabel cLabel1;
    private gnu.chu.controles.CLabel cLabel2;
    private gnu.chu.camposdb.proPanel proPanel1;
    private gnu.chu.camposdb.tidCodi2 tid_codiE;
    // End of variables declaration//GEN-END:variables
}
