/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gnu.chu.anjelica.almacen;

import gnu.chu.controles.CPanel;
import gnu.chu.sql.DatosTabla;
import gnu.chu.utilidades.ventana;
import java.sql.SQLException;
import java.sql.Types;


public class PCabPartes extends CPanel
{

    /**
     * Creates new form PCabPartes
     */
    public PCabPartes() {
        initComponents();
    }
    public void setVisibleFechas(boolean swVisFechas)
    {
        Pfechas.setVisible(swVisFechas);
        Pusuarios.setVisible(swVisFechas);
    }
    public void iniciar(ventana papa,DatosTabla dt) throws SQLException
    {
        prv_codiE.iniciar(dt,papa,papa.vl,papa.EU);
        cli_codiE.iniciar(dt,papa,papa.vl,papa.EU);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        par_codiL = new gnu.chu.controles.CLabel();
        par_codiE = new gnu.chu.controles.CTextField(Types.DECIMAL,"#####9");
        par_fecalt1E = new gnu.chu.controles.CTextField(Types.CHAR,"X",5);
        Pusuarios = new gnu.chu.controles.CPanel();
        par_codiL3 = new gnu.chu.controles.CLabel();
        pac_usuincE2 = new gnu.chu.controles.CTextField(Types.CHAR,"X",15);
        par_codiL2 = new gnu.chu.controles.CLabel();
        pac_usuproE = new gnu.chu.controles.CTextField(Types.CHAR,"X",15);
        par_codiL1 = new gnu.chu.controles.CLabel();
        pac_usuresE = new gnu.chu.controles.CTextField(Types.CHAR,"X",15);
        Pfechas = new gnu.chu.controles.CPanel();
        par_fecaltL1 = new gnu.chu.controles.CLabel();
        par_fecincE = new gnu.chu.controles.CTextField(Types.DATE,"dd-MM-yy");
        par_fecaltL3 = new gnu.chu.controles.CLabel();
        pac_fecproL = new gnu.chu.controles.CLabel();
        pac_fecproE = new gnu.chu.controles.CTextField(Types.DATE,"dd-MM-yy");
        pac_fecresE = new gnu.chu.controles.CTextField(Types.DATE,"dd-MM-yy");
        par_fecaltL2 = new gnu.chu.controles.CLabel();
        pac_estadE = new gnu.chu.controles.CComboBox();
        par_fecaltL4 = new gnu.chu.controles.CLabel();
        par_fecaltL5 = new gnu.chu.controles.CLabel();
        pac_tipoE = new gnu.chu.controles.CComboBox();
        par_fecaltL6 = new gnu.chu.controles.CLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pac_comentE = new gnu.chu.controles.CTextArea();
        pac_cliprvL = new gnu.chu.controles.CLabel();
        cli_codiE = new gnu.chu.camposdb.cliPanel();
        prv_codiE = new gnu.chu.camposdb.prvPanel();
        cLabel2 = new gnu.chu.controles.CLabel();
        pac_fecaltE = new gnu.chu.controles.CTextField(Types.DATE,"dd-MM-yy");
        pac_docanoE = new gnu.chu.controles.CTextField(Types.DECIMAL,"###9");
        pac_docserE = new gnu.chu.controles.CTextField(Types.CHAR,"X");
        pac_docnumE = new gnu.chu.controles.CTextField(Types.DECIMAL,"#####9");

        setLayout(null);

        par_codiL.setText("Parte");
        add(par_codiL);
        par_codiL.setBounds(10, 2, 29, 17);
        add(par_codiE);
        par_codiE.setBounds(50, 2, 50, 17);
        add(par_fecalt1E);
        par_fecalt1E.setBounds(150, 30, 50, 17);

        Pusuarios.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Usuarios")));
        Pusuarios.setLayout(null);

        par_codiL3.setText("Generador");
        Pusuarios.add(par_codiL3);
        par_codiL3.setBounds(10, 20, 70, 17);

        pac_usuincE2.setMinusc(true);
        Pusuarios.add(pac_usuincE2);
        pac_usuincE2.setBounds(90, 20, 100, 17);

        par_codiL2.setText("Procesado");
        Pusuarios.add(par_codiL2);
        par_codiL2.setBounds(10, 40, 70, 17);

        pac_usuproE.setMinusc(true);
        Pusuarios.add(pac_usuproE);
        pac_usuproE.setBounds(90, 40, 100, 17);

        par_codiL1.setText("Resuelto");
        Pusuarios.add(par_codiL1);
        par_codiL1.setBounds(10, 60, 70, 17);

        pac_usuresE.setMinusc(true);
        Pusuarios.add(pac_usuresE);
        pac_usuresE.setBounds(90, 60, 100, 17);

        add(Pusuarios);
        Pusuarios.setBounds(10, 100, 210, 85);

        Pfechas.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Fechas"));
        Pfechas.setLayout(null);

        par_fecaltL1.setText("Resuelto");
        Pfechas.add(par_fecaltL1);
        par_fecaltL1.setBounds(10, 60, 60, 15);
        Pfechas.add(par_fecincE);
        par_fecincE.setBounds(75, 20, 60, 17);

        par_fecaltL3.setText("Creación");
        Pfechas.add(par_fecaltL3);
        par_fecaltL3.setBounds(10, 20, 60, 15);

        pac_fecproL.setText("Procesado");
        Pfechas.add(pac_fecproL);
        pac_fecproL.setBounds(10, 40, 60, 15);
        Pfechas.add(pac_fecproE);
        pac_fecproE.setBounds(75, 40, 60, 17);
        Pfechas.add(pac_fecresE);
        pac_fecresE.setBounds(75, 60, 60, 17);

        add(Pfechas);
        Pfechas.setBounds(530, 100, 150, 85);

        par_fecaltL2.setText("Fecha Alta");
        add(par_fecaltL2);
        par_fecaltL2.setBounds(10, 30, 60, 17);

        pac_estadE.addItem("Generada", "G");
        pac_estadE.addItem("Procesada", "P");
        pac_estadE.addItem("Resuelta", "R");
        add(pac_estadE);
        pac_estadE.setBounds(80, 50, 120, 17);

        par_fecaltL4.setText("Comentario");
        add(par_fecaltL4);
        par_fecaltL4.setBounds(260, 0, 80, 17);

        par_fecaltL5.setText("Tipo");
        add(par_fecaltL5);
        par_fecaltL5.setBounds(110, 2, 40, 17);

        pac_estadE.addItem("Entrada", "E");
        pac_estadE.addItem("Devolucion", "D");
        pac_estadE.addItem("No-Recepcion", "N");
        pac_estadE.addItem("Sala", "S");
        add(pac_tipoE);
        pac_tipoE.setBounds(140, 2, 110, 17);

        par_fecaltL6.setText("Estado");
        add(par_fecaltL6);
        par_fecaltL6.setBounds(30, 50, 40, 17);

        pac_comentE.setColumns(20);
        pac_comentE.setRows(5);
        jScrollPane1.setViewportView(pac_comentE);

        add(jScrollPane1);
        jScrollPane1.setBounds(260, 20, 420, 50);

        pac_cliprvL.setText("Proveedor");
        add(pac_cliprvL);
        pac_cliprvL.setBounds(10, 75, 70, 17);
        add(cli_codiE);
        cli_codiE.setBounds(80, 75, 370, 18);
        add(prv_codiE);
        prv_codiE.setBounds(80, 75, 370, 18);

        cLabel2.setText("Documento");
        add(cLabel2);
        cLabel2.setBounds(480, 75, 70, 17);
        add(pac_fecaltE);
        pac_fecaltE.setBounds(80, 30, 60, 17);
        add(pac_docanoE);
        pac_docanoE.setBounds(550, 75, 40, 17);

        pac_docserE.setAutoNext(true);
        pac_docserE.setMayusc(true);
        add(pac_docserE);
        pac_docserE.setBounds(600, 75, 20, 17);
        add(pac_docnumE);
        pac_docnumE.setBounds(620, 75, 60, 17);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gnu.chu.controles.CPanel Pfechas;
    private gnu.chu.controles.CPanel Pusuarios;
    private gnu.chu.controles.CLabel cLabel2;
    private gnu.chu.camposdb.cliPanel cli_codiE;
    private javax.swing.JScrollPane jScrollPane1;
    private gnu.chu.controles.CLabel pac_cliprvL;
    private gnu.chu.controles.CTextArea pac_comentE;
    private gnu.chu.controles.CTextField pac_docanoE;
    private gnu.chu.controles.CTextField pac_docnumE;
    private gnu.chu.controles.CTextField pac_docserE;
    private gnu.chu.controles.CComboBox pac_estadE;
    private gnu.chu.controles.CTextField pac_fecaltE;
    private gnu.chu.controles.CTextField pac_fecproE;
    private gnu.chu.controles.CLabel pac_fecproL;
    private gnu.chu.controles.CTextField pac_fecresE;
    private gnu.chu.controles.CComboBox pac_tipoE;
    private gnu.chu.controles.CTextField pac_usuincE2;
    private gnu.chu.controles.CTextField pac_usuproE;
    private gnu.chu.controles.CTextField pac_usuresE;
    private gnu.chu.controles.CTextField par_codiE;
    private gnu.chu.controles.CLabel par_codiL;
    private gnu.chu.controles.CLabel par_codiL1;
    private gnu.chu.controles.CLabel par_codiL2;
    private gnu.chu.controles.CLabel par_codiL3;
    private gnu.chu.controles.CTextField par_fecalt1E;
    private gnu.chu.controles.CLabel par_fecaltL1;
    private gnu.chu.controles.CLabel par_fecaltL2;
    private gnu.chu.controles.CLabel par_fecaltL3;
    private gnu.chu.controles.CLabel par_fecaltL4;
    private gnu.chu.controles.CLabel par_fecaltL5;
    private gnu.chu.controles.CLabel par_fecaltL6;
    private gnu.chu.controles.CTextField par_fecincE;
    private gnu.chu.camposdb.prvPanel prv_codiE;
    // End of variables declaration//GEN-END:variables
}
