package gnu.chu.anjelica.listados;

import gnu.chu.Menu.Principal;
import gnu.chu.controles.StatusBar;
import gnu.chu.utilidades.EntornoUsuario;
import gnu.chu.utilidades.Iconos;
import gnu.chu.utilidades.ventana;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.sql.Types;

/**
 * <p>Titulo: RepEtiqueta </p>
 * <p>Descripcion: Permite repetir etiquetas de un producto, cambiando los datos a
 * mostrar. Permite elegir diferentes tipos de etiqueta.
 *
 * </p>
 * <p>Copyright: Copyright (c) 2005-2016</p>
 *
 *  Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo
 *  los términos de la Licencia Publica General de GNU según es publicada por
 *  la Free Software Foundation, bien de la versión 2 de dicha Licencia
 *  o bien (según su elección) de cualquier versión posterior.
 *  Este programa se distribuye con la esperanza de que sea útil,
 *  pero SIN NINGUNA GARANTÍA, incluso sin la garantía MERCANTIL implícita
 *  o sin garantizar la CONVENIENCIA PARA UN PROPÓSITO PARTICULAR.
 *  Véase la Licencia Pública General de GNU para más detalles.
 *  Debería haber recibido una copia de la Licencia Pública General junto con este programa.
 *  Si no ha sido así, escriba a la Free Software Foundation, Inc.,
 *  en 675 Mass Ave, Cambridge, MA 02139, EEUU.
 * @author chuchiP
 * @version 1.1
 */
public class RepEtiqueta extends ventana
{

    public RepEtiqueta(EntornoUsuario eu, Principal p) {
        EU = eu;
        vl = p.panel1;
        jf = p;
        eje = true;

        setTitulo("Repetir Etiquetas");

        try {
            if (jf.gestor.apuntar(this)) {
                jbInit();
            } else {
                setErrorInit(true);
            }
        } catch (Exception e) {
          ErrorInit(e);
        }
    }

    public RepEtiqueta(gnu.chu.anjelica.menu p, EntornoUsuario eu) {

        EU = eu;
        vl = p.getLayeredPane();
        setTitulo("Repetir Etiquetas");
        eje = false;

        try {
            jbInit();
        } catch (Exception e) {
           ErrorInit(e);
        }
    }

    private void jbInit() throws Exception {

        iniciarFrame();

        this.setVersion("2016-07-01");
        statusBar = new StatusBar(this);
        this.getContentPane().add(statusBar, BorderLayout.SOUTH);
        conecta();

        initComponents();
        this.setSize(new Dimension(730, 530));
    }

    @Override
    public void iniciarVentana() throws Exception {
      
        activarEventos();
    }
    private void activarEventos()
    {
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pprinc = new gnu.chu.controles.CPanel();
        cLabel9 = new gnu.chu.controles.CLabel();
        pro_codiE = new gnu.chu.camposdb.proPanel();
        cLabel6 = new gnu.chu.controles.CLabel();
        pro_ejercE = new gnu.chu.controles.CTextField(Types.DECIMAL,"###9");
        cLabel7 = new gnu.chu.controles.CLabel();
        pro_serieE = new gnu.chu.controles.CTextField(Types.CHAR,"X",1);
        cLabel8 = new gnu.chu.controles.CLabel();
        pro_loteE = new gnu.chu.controles.CTextField(Types.DECIMAL,"####9");
        cLabel3 = new gnu.chu.controles.CLabel();
        pro_numindE = new gnu.chu.controles.CTextField(Types.DECIMAL,"####9");
        cLabel4 = new gnu.chu.controles.CLabel();
        deo_kilosE = new gnu.chu.controles.CTextField(Types.DECIMAL, "--,--9.99");
        datTrazPanel1 = new gnu.chu.camposdb.DatTrazPanel();
        Bconsulta = new gnu.chu.controles.CButton(Iconos.getImageIcon("check"));
        BListado = new gnu.chu.controles.CButtonMenu();
        cLabel10 = new gnu.chu.controles.CLabel();
        numEtiqE = new gnu.chu.controles.CTextField(Types.DECIMAL,"###9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Pprinc.setLayout(null);

        cLabel9.setText("Producto");
        Pprinc.add(cLabel9);
        cLabel9.setBounds(10, 10, 60, 17);
        Pprinc.add(pro_codiE);
        pro_codiE.setBounds(70, 10, 340, 17);

        cLabel6.setText("Num. Etiquetas ");
        Pprinc.add(cLabel6);
        cLabel6.setBounds(10, 220, 90, 17);
        Pprinc.add(pro_ejercE);
        pro_ejercE.setBounds(40, 30, 40, 17);

        cLabel7.setText("Serie");
        Pprinc.add(cLabel7);
        cLabel7.setBounds(90, 30, 40, 17);

        pro_serieE.setAutoNext(true);
        pro_serieE.setMayusc(true);
        Pprinc.add(pro_serieE);
        pro_serieE.setBounds(130, 30, 20, 17);

        cLabel8.setText("Lote");
        Pprinc.add(cLabel8);
        cLabel8.setBounds(160, 30, 30, 17);
        Pprinc.add(pro_loteE);
        pro_loteE.setBounds(190, 30, 40, 17);

        cLabel3.setText("Kilos");
        Pprinc.add(cLabel3);
        cLabel3.setBounds(320, 30, 30, 17);
        Pprinc.add(pro_numindE);
        pro_numindE.setBounds(270, 30, 40, 17);

        cLabel4.setText("Ind");
        Pprinc.add(cLabel4);
        cLabel4.setBounds(240, 30, 25, 17);
        Pprinc.add(deo_kilosE);
        deo_kilosE.setBounds(360, 30, 50, 17);

        datTrazPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Pprinc.add(datTrazPanel1);
        datTrazPanel1.setBounds(0, 60, 510, 150);

        Bconsulta.setText("Consultar");
        Bconsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BconsultaActionPerformed(evt);
            }
        });
        Pprinc.add(Bconsulta);
        Bconsulta.setBounds(420, 20, 70, 30);
        Pprinc.add(BListado);
        BListado.setBounds(180, 220, 140, 26);

        cLabel10.setText("Ejerc");
        Pprinc.add(cLabel10);
        cLabel10.setBounds(10, 30, 30, 17);

        numEtiqE.setText("1");
        Pprinc.add(numEtiqE);
        numEtiqE.setBounds(100, 220, 40, 17);

        getContentPane().add(Pprinc, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BconsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BconsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BconsultaActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gnu.chu.controles.CButtonMenu BListado;
    private gnu.chu.controles.CButton Bconsulta;
    private gnu.chu.controles.CPanel Pprinc;
    private gnu.chu.controles.CLabel cLabel10;
    private gnu.chu.controles.CLabel cLabel3;
    private gnu.chu.controles.CLabel cLabel4;
    private gnu.chu.controles.CLabel cLabel6;
    private gnu.chu.controles.CLabel cLabel7;
    private gnu.chu.controles.CLabel cLabel8;
    private gnu.chu.controles.CLabel cLabel9;
    private gnu.chu.camposdb.DatTrazPanel datTrazPanel1;
    private gnu.chu.controles.CTextField deo_kilosE;
    private gnu.chu.controles.CTextField numEtiqE;
    private gnu.chu.camposdb.proPanel pro_codiE;
    private gnu.chu.controles.CTextField pro_ejercE;
    private gnu.chu.controles.CTextField pro_loteE;
    private gnu.chu.controles.CTextField pro_numindE;
    private gnu.chu.controles.CTextField pro_serieE;
    // End of variables declaration//GEN-END:variables
}
