package gnu.chu.anjelica.pad;
/**
 *
 * <p>Titulo: MantVehiculos  </p>
 * <p>Descripción: Mantenimiento Vehiculos</p>
 * <p>Copyright: Copyright (c) 2005-2016
 *  Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo
 *  los terminos de la Licencia Pública General de GNU según es publicada por
 *  la Free Software Foundation, bien de la versión 2 de dicha Licencia
 *  o bien (según su elección) de cualquier versión posterior.
 *  Este programa se distribuye con la esperanza de que sea útil,
 *  pero SIN NINGUNA GARANTIA, incluso sin la garantía MERCANTIL implícita
 *  o sin garantizar la CONVENIENCIA PARA UN PROPOSITO PARTICULAR.
 *  Véase la Licencia Pública General de GNU para más detalles.
 *  Debería haber recibido una copia de la Licencia Pública General junto con este programa.
 *  Si no ha sido así, escriba a la Free Software Foundation, Inc.,
 *  en 675 Mass Ave, Cambridge, MA 02139, EEUU.
 * </p>
 * @author chuchiP
 * @version 1.0 Realizado el mantenimiento.
 *
 */
import gnu.chu.Menu.Principal;
import gnu.chu.controles.StatusBar;
import gnu.chu.interfaces.PAD;
import gnu.chu.sql.DatosTabla;
import gnu.chu.utilidades.EntornoUsuario;
import gnu.chu.utilidades.Iconos;
import gnu.chu.utilidades.navegador;
import gnu.chu.utilidades.ventanaPad;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.net.UnknownHostException;
import java.sql.SQLException;
import java.sql.Types;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Hashtable;

public class MantVehiculos extends   ventanaPad  implements PAD
{
    boolean modConsulta=false;
    String s;
   
    public MantVehiculos(EntornoUsuario eu, Principal p) {
        this(eu, p, null);
    }

    public MantVehiculos(EntornoUsuario eu, Principal p, Hashtable<String,String> ht) {
        EU = eu;
        vl = p.panel1;
        jf = p;
        eje = true;

        try
        {
            if (ht != null)
            {
                if (ht.get("modConsulta") != null)
                    modConsulta = Boolean.valueOf(ht.get("modConsulta"));
            }
            setTitulo("Mantenimiento Vehiculos");
            if (jf.gestor.apuntar(this))
                jbInit();
            else
                setErrorInit(true);
        } catch (Exception e)
        {
          ErrorInit(e);
        }
    }

    public MantVehiculos(gnu.chu.anjelica.menu p, EntornoUsuario eu, Hashtable<String,String> ht) {
        EU = eu;
        vl = p.getLayeredPane();
        eje = false;

        try
        {
            if (ht != null)
            {
                if (ht.get("modConsulta") != null)
                {
                    modConsulta = Boolean.valueOf(ht.get("modConsulta"));
                }
            }
            setTitulo("Mantenimiento Vehiculos");
            jbInit();
        } catch (Exception e)
        {
           ErrorInit(e);
        }
    }

    private void jbInit() throws Exception {
        statusBar = new StatusBar(this);
        nav = new navegador(this, dtCons, false, modConsulta ? navegador.CURYCON : navegador.NORMAL);
        iniciarFrame();
        this.setResizable(false);

        this.setVersion("2016-03-18" + (modConsulta ? "SOLO LECTURA" : ""));
        strSql = "SELECT * FROM vehiculos  "
            + " ORDER BY veh_codi ";

        this.getContentPane().add(nav, BorderLayout.NORTH);
        this.getContentPane().add(statusBar, BorderLayout.SOUTH);
        this.setPad(this);
        dtCons.setLanzaDBCambio(false);
        initComponents();
        iniciarBotones(Baceptar, Bcancelar);

        conecta();
        navActivarAll();
        this.setSize(413, 229);
        activar(false);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pprinc = new gnu.chu.controles.CPanel();
        cLabel1 = new gnu.chu.controles.CLabel();
        veh_codiE = new gnu.chu.controles.CTextField(Types.DECIMAL,"###9");
        cLabel3 = new gnu.chu.controles.CLabel();
        veh_nombE = new gnu.chu.controles.CTextField(Types.CHAR,"40",50);
        cLabel5 = new gnu.chu.controles.CLabel();
        veh_anocomE = new gnu.chu.controles.CTextField(Types.DECIMAL,"###9");
        cLabel6 = new gnu.chu.controles.CLabel();
        veh_matriE = new gnu.chu.controles.CTextField(Types.CHAR,"X",15);
        Bcancelar = new gnu.chu.controles.CButton(Iconos.getImageIcon("cancel"));
        Baceptar = new gnu.chu.controles.CButton(Iconos.getImageIcon("check"));
        cLabel7 = new gnu.chu.controles.CLabel();
        veh_marcaE = new gnu.chu.controles.CTextField(Types.CHAR,"X",25);
        cLabel8 = new gnu.chu.controles.CLabel();
        veh_kilomeE = new gnu.chu.controles.CTextField(Types.DECIMAL,"####,##9");
        cLabel4 = new gnu.chu.controles.CLabel();
        veh_modeloE = new gnu.chu.controles.CTextField(Types.CHAR,"X",25);

        Pprinc.setLayout(null);

        cLabel1.setText("Codigo");
        Pprinc.add(cLabel1);
        cLabel1.setBounds(10, 2, 49, 15);
        Pprinc.add(veh_codiE);
        veh_codiE.setBounds(70, 0, 42, 17);

        cLabel3.setText("Marca");
        Pprinc.add(cLabel3);
        cLabel3.setBounds(10, 40, 50, 17);
        Pprinc.add(veh_nombE);
        veh_nombE.setBounds(70, 20, 250, 17);

        cLabel5.setText("Año Compra");
        Pprinc.add(cLabel5);
        cLabel5.setBounds(230, 80, 80, 17);
        Pprinc.add(veh_anocomE);
        veh_anocomE.setBounds(310, 80, 50, 17);

        cLabel6.setText("Matricula");
        Pprinc.add(cLabel6);
        cLabel6.setBounds(10, 80, 60, 17);

        veh_matriE.setMayusc(true);
        Pprinc.add(veh_matriE);
        veh_matriE.setBounds(70, 80, 120, 17);

        Bcancelar.setText("Cancelar");
        Pprinc.add(Bcancelar);
        Bcancelar.setBounds(230, 120, 103, 34);

        Baceptar.setText("Aceptar");
        Pprinc.add(Baceptar);
        Baceptar.setBounds(60, 120, 104, 34);

        cLabel7.setText("Nombre");
        Pprinc.add(cLabel7);
        cLabel7.setBounds(10, 25, 49, 15);
        Pprinc.add(veh_marcaE);
        veh_marcaE.setBounds(70, 40, 150, 17);

        cLabel8.setText("Km. Actuales");
        Pprinc.add(cLabel8);
        cLabel8.setBounds(10, 100, 90, 17);
        Pprinc.add(veh_kilomeE);
        veh_kilomeE.setBounds(100, 100, 90, 17);

        cLabel4.setText("Modelo");
        Pprinc.add(cLabel4);
        cLabel4.setBounds(10, 60, 50, 17);
        Pprinc.add(veh_modeloE);
        veh_modeloE.setBounds(70, 60, 150, 17);

        getContentPane().add(Pprinc, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gnu.chu.controles.CButton Baceptar;
    private gnu.chu.controles.CButton Bcancelar;
    private gnu.chu.controles.CPanel Pprinc;
    private gnu.chu.controles.CLabel cLabel1;
    private gnu.chu.controles.CLabel cLabel3;
    private gnu.chu.controles.CLabel cLabel4;
    private gnu.chu.controles.CLabel cLabel5;
    private gnu.chu.controles.CLabel cLabel6;
    private gnu.chu.controles.CLabel cLabel7;
    private gnu.chu.controles.CLabel cLabel8;
    private gnu.chu.controles.CTextField veh_anocomE;
    private gnu.chu.controles.CTextField veh_codiE;
    private gnu.chu.controles.CTextField veh_kilomeE;
    private gnu.chu.controles.CTextField veh_marcaE;
    private gnu.chu.controles.CTextField veh_matriE;
    private gnu.chu.controles.CTextField veh_modeloE;
    private gnu.chu.controles.CTextField veh_nombE;
    // End of variables declaration//GEN-END:variables

    @Override
    public void PADPrimero() {
        verDatos();
    }

    @Override
    public void PADAnterior() {
         verDatos();
    }

    @Override
    public void PADSiguiente() {
         verDatos();
    }

    @Override
    public void PADUltimo() {
        verDatos();
    }
    @Override
    public boolean checkAddNew()
    {
        try {
          if (getRegistro(veh_codiE.getValorInt(), dtStat))
          {
              mensajeErr("Codigo de vehiculo ya esta en uso");
              veh_codiE.requestFocus();
              return false;
          }
         
        } catch (SQLException k)
        {
           Error("Error al comprobrar registro",k); 
        }
        return checkEdit();
    }
    @Override
    public boolean checkEdit()
 {
     if (veh_nombE.isNull())
     {
         mensajeErr("Introduzca Nombre de Vehiculo");
         veh_nombE.requestFocus();
         return false;
     }
     if (veh_marcaE.isNull())
     {
         mensajeErr("Introduzca Marca de Vehiculo");
         veh_marcaE.requestFocus();
         return false;
     }
     if (veh_matriE.isNull())
     {
         mensajeErr("Introduzca Martricula de Vehiculo");
         veh_matriE.requestFocus();
         return false;
     }
   
 
     return true;
    }
    @Override
    public void ej_edit1() {
        try
   {
     dtAdd.edit();
     actDatos(dtAdd);
     resetBloqueo(dtAdd,"vehiculos", veh_codiE.getText());
     ctUp.commit();
   }
   catch (Throwable ex)
   {
     Error("Error al Modificar datos", ex);
     return;
   }
   mensaje("");
   mensajeErr("Datos ... Modificados");
   activaTodo();
   verDatos();
    }
   void actDatos(DatosTabla dt) throws Exception {
        dt.setDato("veh_nomb", veh_nombE.getText());
        dt.setDato("veh_marca", veh_marcaE.getText());
        dt.setDato("veh_modelo", veh_modeloE.getText());
        dt.setDato("veh_matri", veh_matriE.getText());
        dt.setDato("veh_anocom", veh_anocomE.getValorInt());
        dt.setDato("veh_kilome", veh_kilomeE.getValorInt());
        dt.update();
   }
    @Override
    public void canc_edit() {
        mensaje("");
        try
        {
            resetBloqueo(dtAdd, "vehiculos", veh_codiE.getText());
        }
        catch (Exception ex)
        {
            Error("Error al Quitar Bloqueo", ex);
            return;
        }
        mensajeErr("Modificacion de Datos Cancelada");
        activaTodo();
        verDatos();
    }

    
    @Override
    public void ej_addnew1() {
          try {
           
            dtAdd.addNew("vehiculos");
            dtAdd.setDato("veh_codi", veh_codiE.getText());

            actDatos(dtAdd);
           
            dtAdd.commit();
            mensajeErr("Alta ... REALIZADA");
            mensaje("");
            activaTodo();
        } catch (Exception k) {
            Error("Error al Insertar Pais", k);
        }
    }

    @Override
    public void canc_addnew() {
        mensaje("");
        mensajeErr("Cancelada Alta ...");
        verDatos();
        activaTodo();
    }

    @Override
    public void activar(boolean b) {
       veh_codiE.setEnabled(b);
       veh_nombE.setEnabled(b);
       veh_marcaE.setEnabled(b);
       veh_modeloE.setEnabled(b);
       veh_matriE.setEnabled(b);
       veh_anocomE.setEnabled(b);
       veh_kilomeE.setEnabled(b);
       Bcancelar.setEnabled(b);
       Baceptar.setEnabled(b);
    }
    @Override
    public void iniciarVentana() throws Exception {
        Pprinc.setButton(KeyEvent.VK_F4, Baceptar);
        veh_codiE.setColumnaAlias("veh_codi");
        veh_nombE.setColumnaAlias("veh_nomb");
        veh_marcaE.setColumnaAlias("veh_marca");        
        veh_modeloE.setColumnaAlias("veh_modelo");       
        veh_matriE.setColumnaAlias("veh_matri");
        veh_anocomE.setColumnaAlias("veh_anocom");
        veh_kilomeE.setColumnaAlias("veh_kilome");
        
        verDatos();
    }
    void verDatos()
    {
        try
        {
            if (dtCons.getNOREG())
                return;
            if (! getRegistro(dtCons.getInt("veh_codi"),dtStat))
            {
                Pprinc.resetTexto();
                veh_codiE.setValorInt(dtCons.getInt("veh_codi"));
                msgBox("Datos de Vehiculo: "+veh_codiE.getValorInt()+" No encontrados");
                return;
            }
            veh_codiE.setValorInt(dtStat.getInt("veh_codi"));
            veh_nombE.setText(dtStat.getString("veh_nomb"));
            veh_marcaE.setText(dtStat.getString("veh_marca"));            
            veh_modeloE.setText(dtStat.getString("veh_modelo"));            
            veh_matriE.setText(dtStat.getString("veh_matri"));
            veh_anocomE.setText(dtStat.getString("veh_anocom"));
            veh_kilomeE.setText(dtStat.getString("veh_kilome"));
        } catch (SQLException k)
        {
            Error("Error al ver datos de vehiculos",k);
        }
    }
     @Override
    public void PADQuery() {
//        System.out.println("Alto: "+this.getSize().height+" Ancho: "+this.getSize().width);
        activar(true);
      
        Pprinc.setQuery(true);
        Pprinc.resetTexto();
       
        mensajeErr("Introduzca criterios para Filtro de Busqueda");
        veh_codiE.requestFocus();
    }
    @Override
    public void ej_query1(){
     Component c;
     if ( (c = Pprinc.getErrorConf()) != null)
     {
        c.requestFocus();
        mensaje("Error en Criterios de busqueda");
        return;
     }
   

    ArrayList v = new ArrayList();
    v.add(veh_codiE.getStrQuery());
    v.add(veh_nombE.getStrQuery());
    v.add(veh_marcaE.getStrQuery());
    v.add(veh_modeloE.getStrQuery());
    v.add(veh_matriE.getStrQuery());
    v.add(veh_anocomE.getStrQuery());
    v.add(veh_kilomeE.getStrQuery());
    

    s = "SELECT * FROM vehiculos ";
    s = creaWhere(s, v,true);
    s+=" ORDER BY veh_codi ";
    Pprinc.setQuery(false);
    
    try
    {
      if (!dtCons.select(s))
      {
        mensaje("");
        mensajeErr("No encontrados Registros para estos criterios");
        rgSelect();
        activaTodo();
        verDatos();
        return;
      }
      mensaje("");
      strSql = s;
      activaTodo();
      rgSelect();
      verDatos();
      mensajeErr("Nuevos registros selecionados");
    }
    catch (Exception ex)
    {
      fatalError("Error al buscar Representantes: ", ex);
    }

 }
    @Override
  public void PADAddNew(){
  
   activar(true);
   mensaje("Insertando Vehiculo ...");
   Pprinc.resetTexto();
   s="select max(veh_codi) as veh_codi from vehiculos";
   try
   {
    dtStat.select(s);
    veh_codiE.setValorInt(dtStat.getInt("veh_codi",true)+1);
   } catch (SQLException k)
   {
       Error("Error al buscar siguiente codigo de Vehiculo",k);
   }
   veh_codiE.resetCambio();
   veh_codiE.requestFocus();
 }
@Override
 public void PADEdit(){
   activar(true);
   try
   {
     if ( ! lockRegistro())
            return;
   }
   catch (UnknownHostException | SQLException | ParseException k)
   {
     Error("Error al bloquear el registro", k);
     return;
   }
   veh_codiE.setEnabled(false);
   veh_nombE.requestFocus();
   veh_codiE.resetCambio();
   mensaje("Modificando datos de registro activo ...");
 }
 @Override
 public void PADDelete(){
     try
     {
       if (! lockRegistro())
           return;
     }
     catch (UnknownHostException | SQLException | ParseException k)
     {
       Error("Error al bloquear el registro", k);
       return;
     }
     Baceptar.setEnabled(true);
     Bcancelar.setEnabled(true);
     Bcancelar.requestFocus();
     mensaje("Borrar registro activo ...");
 }
    @Override
 public void ej_delete1(){
   try
     {
       dtAdd.delete(stUp);
       
       resetBloqueo(dtAdd, "vehiculos", veh_codiE.getText());
       ctUp.commit();
       rgSelect();
     }
     catch (Exception ex)
     {
       Error("Error al borrar Registro",ex);
     }
     activaTodo();
     verDatos();
     mensaje("");
     mensajeErr("Registro ... Borrado");
 }

 public void canc_delete(){
   mensaje("");
   try
   {
     resetBloqueo(dtAdd, "vehiculos", veh_codiE.getText());
   }
   catch (Exception ex)
   {
     Error("Error al Quitar Bloqueo", ex);
     return;
   }
   mensajeErr("Borrado de Datos Cancelada");
   activaTodo();
   verDatos();
 }
  private boolean lockRegistro() throws UnknownHostException, SQLException, ParseException {
        if (!setBloqueo(dtAdd, "vehiculos", veh_codiE.getText())) {
            msgBox(msgBloqueo);
            nav.pulsado = navegador.NINGUNO;
            activaTodo();
            dtAdd.getConexion().rollback();
            return false;
        }
        if (!dtAdd.select("SELECT * FROM vehiculos WHERE veh_codi = " + veh_codiE.getText() , true)) {
            mensajeErr("Registro ha sido borrado");
            resetBloqueo(dtAdd, "vehiculos", veh_codiE.getText());
            activaTodo();
            mensaje("");
            return false;
        }
        return true;
    }
 @Override
 public void canc_query(){
   Pprinc.setQuery(false);

   activaTodo();
   verDatos();
   mensajeErr("Introducion filtro busqueda ... CANCELADO");
   mensaje("");
 }
    /**
     * Devuelve en el datostabla mandado el registro que indica el vehiculo mandado
     * @param vehCodi
     * @param dt
     * @return true si encuentra el registro.
     * @throws SQLException 
     */
    public static boolean getRegistro(int vehCodi, DatosTabla dt) throws SQLException
    {
        return dt.select("select * from vehiculos where veh_codi = "+vehCodi);
    }
    
   
    public static String getNombreVehiculo(int vehCodi, DatosTabla dt) throws SQLException
    {
        if (! dt.select("select * from vehiculos where veh_codi = "+vehCodi))
            return null;
        return dt.getString("veh_nomb");
    }
 
}
