

/**
 *
 * <p>Titulo: pdnumeracion  </p>
 * <p>Descripción: Mantenimiento Numeraciones</p>
 * <p>Copyright: Copyright (c) 2005
 *  Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo
 *  los terminos de la Licencia P�blica General de GNU seg�n es publicada por
 *  la Free Software Foundation, bien de la versión 2 de dicha Licencia
 *  o bien (según su elección) de cualquier versión posterior.
 *  Este programa se distribuye con la esperanza de que sea útil,
 *  pero SIN NINGUNA GARANTIA, incluso sin la garantía MERCANTIL implícita
 *  o sin garantizar la CONVENIENCIA PARA UN PROPOSITO PARTICULAR.
 *  Véase la Licencia Pública General de GNU para más detalles.
 *  Debería haber recibido una copia de la Licencia Pública General junto con este programa.
 *  Si no ha sido así, escriba a la Free Software Foundation, Inc.,
 *  en 675 Mass Ave, Cambridge, MA 02139, EEUU.
 * </p>
 * @author chuchiP
 * @version 1.0 Realizado el mantenimiento.
 * @version 1.1 Incluidos campos de numera fra y numero de alb = fra
 *
 */
package gnu.chu.anjelica.pad;

import gnu.chu.controles.*;
import gnu.chu.utilidades.*;
import java.sql.*;
import gnu.chu.Menu.*;
import java.awt.*;
import java.util.*;
import gnu.chu.interfaces.*;
import gnu.chu.utilidades.ventanaPad;
import gnu.chu.sql.DatosTabla;
import java.awt.event.KeyEvent;

public class pdnumeracion extends  ventanaPad  implements PAD {
  String s;
  boolean modConsulta = true;
public pdnumeracion(EntornoUsuario eu, Principal p)
 {
   this(eu, p, null);
 }

 public pdnumeracion(EntornoUsuario eu, Principal p,Hashtable ht)
 {
   EU = eu;
   vl = p.panel1;
   jf = p;
   eje = true;

   try
   {
     if (ht != null)
     {
       if (ht.get("modConsulta") != null)
         modConsulta = Boolean.valueOf(ht.get("modConsulta").toString()).
             booleanValue();
     }
     setTitulo("Mantenimiento Numeraciones");
     if (jf.gestor.apuntar(this))
       jbInit();
     else
       setErrorInit(true);
   }
   catch (Exception e)
   {
     e.printStackTrace();
     setErrorInit(true);
   }
 }

    public pdnumeracion(gnu.chu.anjelica.menu p, EntornoUsuario eu, Hashtable ht) {
        EU = eu;
        vl = p.getLayeredPane();
        eje = false;

        try {
            if (ht != null) {
                if (ht.get("modConsulta") != null) {
                    modConsulta = Boolean.valueOf(ht.get("modConsulta").toString()).
                            booleanValue();
                }
            }
            setTitulo("Mant. Numeraciones");


            jbInit();
        } catch (Exception e) {
            e.printStackTrace();
            setErrorInit(true);
        }
    }

    private void jbInit() throws Exception {
        statusBar = new StatusBar(this);
        nav = new navegador(this, dtCons, false, modConsulta ? navegador.CURYCON : navegador.NORMAL);
        iniciarFrame();
       
        this.setVersion("2009-01-24" + (modConsulta ? "SOLO LECTURA" : ""));
        strSql = "SELECT * FROM v_numerac where emp_codi = " + EU.em_cod +
                " ORDER BY eje_nume,emp_codi";

        this.getContentPane().add(nav, BorderLayout.NORTH);
        this.getContentPane().add(statusBar, BorderLayout.SOUTH);
        this.setPad(this);
        navActivarAll();
        dtCons.setLanzaDBCambio(false);
        initComponents();
        iniciarBotones(Baceptar, Bcancelar);

        conecta();
        activar(false);

    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pprinc = new gnu.chu.controles.CPanel();
        Pcabe = new gnu.chu.controles.CPanel();
        emp_codiE = new gnu.chu.camposdb.empPanel();
        cLabel1 = new gnu.chu.controles.CLabel();
        cLabel2 = new gnu.chu.controles.CLabel();
        eje_numeE = new gnu.chu.controles.CTextField(Types.DECIMAL,"###9");
        emp_nombL = emp_codiE.creaLabelEmp();
        Pdatos = new gnu.chu.controles.CPanel();
        PAlbVen = new gnu.chu.controles.CPanel();
        cLabel3 = new gnu.chu.controles.CLabel();
        num_serieaE = new gnu.chu.controles.CTextField(Types.DECIMAL,"###,##9");
        cLabel4 = new gnu.chu.controles.CLabel();
        num_seriecE = new gnu.chu.controles.CTextField(Types.DECIMAL,"###,##9");
        cLabel5 = new gnu.chu.controles.CLabel();
        num_seriebE = new gnu.chu.controles.CTextField(Types.DECIMAL,"###,##9");
        cLabel6 = new gnu.chu.controles.CLabel();
        num_seriedE = new gnu.chu.controles.CTextField(Types.DECIMAL,"###,##9");
        cLabel7 = new gnu.chu.controles.CLabel();
        num_seriexE = new gnu.chu.controles.CTextField(Types.DECIMAL,"###,##9");
        cLabel8 = new gnu.chu.controles.CLabel();
        num_serieyE = new gnu.chu.controles.CTextField(Types.DECIMAL,"###,##9");
        PFraVen = new gnu.chu.controles.CPanel();
        cLabel9 = new gnu.chu.controles.CLabel();
        num_facturE = new gnu.chu.controles.CTextField(Types.DECIMAL,"###,##9");
        cLabel10 = new gnu.chu.controles.CLabel();
        num_factucE = new gnu.chu.controles.CTextField(Types.DECIMAL,"###,##9");
        cLabel11 = new gnu.chu.controles.CLabel();
        num_factubE = new gnu.chu.controles.CTextField(Types.DECIMAL,"###,##9");
        cLabel12 = new gnu.chu.controles.CLabel();
        num_factudE = new gnu.chu.controles.CTextField(Types.DECIMAL,"###,##9");
        PAlbCom = new gnu.chu.controles.CPanel();
        cLabel15 = new gnu.chu.controles.CLabel();
        num_secomaE = new gnu.chu.controles.CTextField(Types.DECIMAL,"###,##9");
        cLabel16 = new gnu.chu.controles.CLabel();
        num_secomcE = new gnu.chu.controles.CTextField(Types.DECIMAL,"###,##9");
        cLabel17 = new gnu.chu.controles.CLabel();
        num_secombE = new gnu.chu.controles.CTextField(Types.DECIMAL,"###,##9");
        cLabel18 = new gnu.chu.controles.CLabel();
        num_secomdE = new gnu.chu.controles.CTextField(Types.DECIMAL,"###,##9");
        cLabel19 = new gnu.chu.controles.CLabel();
        num_secomyE = new gnu.chu.controles.CTextField(Types.DECIMAL,"###,##9");
        cLabel20 = new gnu.chu.controles.CLabel();
        cLabel21 = new gnu.chu.controles.CLabel();
        cLabel22 = new gnu.chu.controles.CLabel();
        cLabel23 = new gnu.chu.controles.CLabel();
        num_despiE = new gnu.chu.controles.CTextField(Types.DECIMAL,"###,##9");
        num_remesaE = new gnu.chu.controles.CTextField(Types.DECIMAL,"###,##9");
        num_pedcomE = new gnu.chu.controles.CTextField(Types.DECIMAL,"###,##9");
        num_faccomE = new gnu.chu.controles.CTextField(Types.DECIMAL,"###,##9");
        Baceptar = new gnu.chu.controles.CButton();
        Bcancelar = new gnu.chu.controles.CButton();

        Pcabe.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cLabel1.setText("Empresa");

        cLabel2.setText("Ejercicio");

        eje_numeE.setText("2008");

        emp_nombL.setText("cLabel24");

        org.jdesktop.layout.GroupLayout PcabeLayout = new org.jdesktop.layout.GroupLayout(Pcabe);
        Pcabe.setLayout(PcabeLayout);
        PcabeLayout.setHorizontalGroup(
            PcabeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PcabeLayout.createSequentialGroup()
                .add(8, 8, 8)
                .add(PcabeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(cLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(PcabeLayout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(cLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(PcabeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(emp_codiE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(eje_numeE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(emp_nombL, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 300, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PcabeLayout.setVerticalGroup(
            PcabeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PcabeLayout.createSequentialGroup()
                .add(PcabeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(PcabeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(cLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(emp_nombL, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(emp_codiE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(PcabeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(cLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(eje_numeE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        PcabeLayout.linkSize(new java.awt.Component[] {emp_codiE, emp_nombL}, org.jdesktop.layout.GroupLayout.VERTICAL);

        Pdatos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        PAlbVen.setBorder(javax.swing.BorderFactory.createTitledBorder("Alb.Ventas"));

        cLabel3.setText("Serie A");

        cLabel4.setText("Serie C");

        cLabel5.setText("Serie B");

        cLabel6.setText("Serie D");

        cLabel7.setText("Serie X");

        cLabel8.setText("Serie Y");

        org.jdesktop.layout.GroupLayout PAlbVenLayout = new org.jdesktop.layout.GroupLayout(PAlbVen);
        PAlbVen.setLayout(PAlbVenLayout);
        PAlbVenLayout.setHorizontalGroup(
            PAlbVenLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PAlbVenLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(PAlbVenLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(PAlbVenLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, cLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, cLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(cLabel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(10, 10, 10)
                .add(PAlbVenLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(num_serieaE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(num_seriecE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(num_seriexE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(PAlbVenLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(PAlbVenLayout.createSequentialGroup()
                        .add(27, 27, 27)
                        .add(PAlbVenLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(cLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(cLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(PAlbVenLayout.createSequentialGroup()
                        .add(25, 25, 25)
                        .add(cLabel8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(10, 10, 10)
                .add(PAlbVenLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(num_seriebE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(num_seriedE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(num_serieyE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
        );
        PAlbVenLayout.setVerticalGroup(
            PAlbVenLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PAlbVenLayout.createSequentialGroup()
                .add(PAlbVenLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(num_serieaE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(cLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(num_seriebE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(PAlbVenLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(num_seriecE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(cLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(num_seriedE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(PAlbVenLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cLabel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(num_seriexE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(cLabel8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(num_serieyE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        PFraVen.setBorder(javax.swing.BorderFactory.createTitledBorder("Fra.Ventas"));

        cLabel9.setText("Serie A");

        cLabel10.setText("Serie C");

        cLabel11.setText("Serie B");

        cLabel12.setText("Serie D");

        org.jdesktop.layout.GroupLayout PFraVenLayout = new org.jdesktop.layout.GroupLayout(PFraVen);
        PFraVen.setLayout(PFraVenLayout);
        PFraVenLayout.setHorizontalGroup(
            PFraVenLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PFraVenLayout.createSequentialGroup()
                .addContainerGap()
                .add(PFraVenLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, cLabel10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, cLabel9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(10, 10, 10)
                .add(PFraVenLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(num_facturE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(num_factucE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(27, 27, 27)
                .add(PFraVenLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(cLabel11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(cLabel12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(10, 10, 10)
                .add(PFraVenLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(num_factubE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(num_factudE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        PFraVenLayout.setVerticalGroup(
            PFraVenLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PFraVenLayout.createSequentialGroup()
                .add(PFraVenLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cLabel9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(num_facturE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(cLabel11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(num_factubE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(PFraVenLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cLabel10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(num_factucE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(cLabel12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(num_factudE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
        );

        PAlbCom.setBorder(javax.swing.BorderFactory.createTitledBorder("Alb.Compras"));

        cLabel15.setText("Serie A");

        cLabel16.setText("Serie C");

        cLabel17.setText("Serie B");

        cLabel18.setText("Serie D");

        cLabel19.setText("Serie Y");

        org.jdesktop.layout.GroupLayout PAlbComLayout = new org.jdesktop.layout.GroupLayout(PAlbCom);
        PAlbCom.setLayout(PAlbComLayout);
        PAlbComLayout.setHorizontalGroup(
            PAlbComLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PAlbComLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(PAlbComLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, cLabel16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, cLabel15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(10, 10, 10)
                .add(PAlbComLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(PAlbComLayout.createSequentialGroup()
                        .add(10, 10, 10)
                        .add(cLabel19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(10, 10, 10)
                        .add(num_secomyE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(PAlbComLayout.createSequentialGroup()
                        .add(PAlbComLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(num_secomaE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(num_secomcE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(27, 27, 27)
                        .add(PAlbComLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(cLabel17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(cLabel18, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(10, 10, 10)
                        .add(PAlbComLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(num_secombE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(num_secomdE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
        );
        PAlbComLayout.setVerticalGroup(
            PAlbComLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PAlbComLayout.createSequentialGroup()
                .add(PAlbComLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cLabel15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(num_secomaE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(cLabel17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(num_secombE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(PAlbComLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cLabel16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(num_secomcE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(cLabel18, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(num_secomdE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(PAlbComLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cLabel19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(num_secomyE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cLabel20.setText("Fra.Compras");

        cLabel21.setText("Pedido Compras");

        cLabel22.setText("Numero Remesa");

        cLabel23.setText("Numero Despiece");

        org.jdesktop.layout.GroupLayout PdatosLayout = new org.jdesktop.layout.GroupLayout(Pdatos);
        Pdatos.setLayout(PdatosLayout);
        PdatosLayout.setHorizontalGroup(
            PdatosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PdatosLayout.createSequentialGroup()
                .add(PdatosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, PAlbCom, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, PAlbVen, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .add(18, 18, 18)
                .add(PdatosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(PdatosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                        .add(PdatosLayout.createSequentialGroup()
                            .add(cLabel22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(num_remesaE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(PdatosLayout.createSequentialGroup()
                            .add(cLabel21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(num_pedcomE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(org.jdesktop.layout.GroupLayout.LEADING, PdatosLayout.createSequentialGroup()
                            .add(cLabel20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(45, 45, 45)
                            .add(num_faccomE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(PdatosLayout.createSequentialGroup()
                        .add(cLabel23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(num_despiE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(PFraVen, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        PdatosLayout.setVerticalGroup(
            PdatosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PdatosLayout.createSequentialGroup()
                .add(PdatosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(PAlbVen, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(PFraVen, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(PdatosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(PdatosLayout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(PAlbCom, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(PdatosLayout.createSequentialGroup()
                        .add(16, 16, 16)
                        .add(PdatosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(cLabel20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(num_faccomE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(PdatosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(cLabel21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(num_pedcomE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(PdatosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(cLabel22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(num_remesaE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(PdatosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(cLabel23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(num_despiE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Baceptar.setText("Aceptar");

        Bcancelar.setText("Cancelar");

        org.jdesktop.layout.GroupLayout PprincLayout = new org.jdesktop.layout.GroupLayout(Pprinc);
        Pprinc.setLayout(PprincLayout);
        PprincLayout.setHorizontalGroup(
            PprincLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PprincLayout.createSequentialGroup()
                .add(98, 98, 98)
                .add(Baceptar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 153, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(51, 51, 51)
                .add(Bcancelar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 135, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, PprincLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(Pdatos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(23, 23, 23))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, PprincLayout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .add(Pcabe, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(55, 55, 55))
        );
        PprincLayout.setVerticalGroup(
            PprincLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PprincLayout.createSequentialGroup()
                .add(Pcabe, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(Pdatos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 219, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(PprincLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(Baceptar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(Bcancelar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        getContentPane().add(Pprinc, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void iniciarVentana() throws Exception {
        Pprinc.setButton(KeyEvent.VK_F4, Baceptar);
        emp_codiE.setColumnaAlias("emp_codi");
        eje_numeE.setColumnaAlias("eje_nume");
        num_serieaE.setColumnaAlias("num_seriea");
        num_seriebE.setColumnaAlias("num_serieb");
        num_seriecE.setColumnaAlias("num_seriec");
        num_seriedE.setColumnaAlias("num_seried");
        num_seriexE.setColumnaAlias("num_seriex");
        num_serieyE.setColumnaAlias("num_seriey");
        num_facturE.setColumnaAlias("num_factur");
        num_factubE.setColumnaAlias("num_factub");
        num_factucE.setColumnaAlias("num_factuc");
        num_factudE.setColumnaAlias("num_factud");

        num_secomdE.setColumnaAlias("num_secomd");
        num_secombE.setColumnaAlias("num_secomb");
        num_secomcE.setColumnaAlias("num_secomc");
        num_secomaE.setColumnaAlias("num_secoma");
        num_secomyE.setColumnaAlias("num_secomy");
        num_faccomE.setColumnaAlias("num_faccom");
        num_pedcomE.setColumnaAlias("num_pedcom");
        num_despiE.setColumnaAlias("num_despi");
        num_remesaE.setColumnaAlias("num_remesa");
        verDatos();
    }

    public void PADPrimero() {
        verDatos();
    }

    public void PADAnterior() {
        verDatos();
    }

    public void PADSiguiente() {
        verDatos();
    }

    public void PADUltimo() {
        verDatos();
    }

    public void PADQuery() {
        activar(true);

        Pprinc.setQuery(true);
        Pprinc.resetTexto();
        emp_codiE.setValorInt(EU.em_cod);
        mensajeErr("Introduzca criterios para Filtro de Busqueda");

    }


 public void ej_query1(){
   Component c;
   if ( (c = Pcabe.getErrorConf()) != null)
   {
     c.requestFocus();
     mensaje("Error en Criterios de busqueda");
     return;
   }
   if ( (c = Pdatos.getErrorConf()) != null)
   {
     c.requestFocus();
     mensaje("Error en Criterios de busqueda");
     return;
   }

   Vector v = new Vector();
    v.addElement(emp_codiE.getStrQuery());
    v.addElement(eje_numeE.getStrQuery());
    v.addElement(num_serieaE.getStrQuery());
    v.addElement(num_seriebE.getStrQuery());
    v.addElement(num_seriecE.getStrQuery());
    v.addElement(num_seriedE.getStrQuery());
    v.addElement(num_serieyE.getStrQuery());
    v.addElement(num_facturE.getStrQuery());
    v.addElement(num_factubE.getStrQuery());
    v.addElement(num_factucE.getStrQuery());
    v.addElement(num_factudE.getStrQuery());


    v.addElement(num_secomaE.getStrQuery());
    v.addElement(num_secombE.getStrQuery());
    v.addElement(num_secomyE.getStrQuery());
    v.addElement(num_secomcE.getStrQuery());
    v.addElement(num_secomcE.getStrQuery());
    v.addElement(num_faccomE.getStrQuery());
    v.addElement(num_pedcomE.getStrQuery());
    v.addElement(num_despiE.getStrQuery());
    v.addElement(num_remesaE.getStrQuery());

    s = "SELECT * FROM v_numerac ";
    s = creaWhere(s, v,true);
    s+=" ORDER BY eje_nume,emp_codi ";
    Pcabe.setQuery(false);
    Pdatos.setQuery(false);
//    debug(s);
    try
    {
      if (!dtCons.select(s))
      {
        mensaje("");
        mensajeErr("No encontrados Registros para estos criterios");
        rgSelect();
        activaTodo();
        verDatos();
        return;
      }
      mensaje("");
      strSql = s;
      activaTodo();
      rgSelect();
      verDatos();
      mensajeErr("Nuevos registros selecionados");
    }
    catch (Exception ex)
    {
      fatalError("Error al buscar Numeraciones: ", ex);
    }

 }

 public void canc_query(){
   Pdatos.setQuery(false);
   activaTodo();
   verDatos();
   mensajeErr("Introducion filtro busqueda ... CANCELADO");
   mensaje("");
 }

 public void PADEdit(){
   activar(true);

   try
   {
     if (!setBloqueo(dtAdd, "v_numerac", emp_codiE.getValorInt()+"|"+eje_numeE.getValorDec()))
     {
       msgBox(msgBloqueo);
       nav.pulsado = navegador.NINGUNO;
       activaTodo();
       dtAdd.getConexion().rollback();
       return;
     }

     if (!dtAdd.select("SELECT * FROM v_numerac WHERE emp_codi = " +emp_codiE.getValorInt()+
         " AND eje_nume = "+eje_numeE.getValorInt(), true))
     {
       mensajeErr("Registro ha sido borrado");
       resetBloqueo(dtAdd,"v_numerac", emp_codiE.getValorInt()+"|"+eje_numeE.getValorDec());
       activaTodo();
       mensaje("");
       return;
     }

   }
   catch (Exception k)
   {
     Error("Error al bloquear el registro", k);
     return;
   }
   emp_codiE.requestFocus();
   mensaje("Modificando datos de registro activo ...");
 }

 public void ej_edit1(){
   try
   {
     dtAdd.edit();
     actDatos(dtAdd);
     dtAdd.update(stUp);
     resetBloqueo(dtAdd,"v_numerac", emp_codiE.getValorInt()+"|"+eje_numeE.getValorDec());
     ctUp.commit();
   }
   catch (Throwable ex)
   {
     Error("Error al Modificar datos", ex);
     return;
   }
   mensaje("");
   mensajeErr("Datos ... Modificados");
   activaTodo();
   verDatos();

 }

 public void canc_edit()
 {
   mensaje("");
   try
   {
     resetBloqueo(dtAdd, "v_numerac",
                  emp_codiE.getValorInt() + "|" + eje_numeE.getValorDec());

   }
   catch (Exception ex)
   {
     Error("Error al Quitar Bloquo", ex);
     return;
   }
   mensajeErr("Modificacion de Datos Cancelada");
   activaTodo();
   verDatos();
 }


 public void PADAddNew(){
   activar(true);
   mensaje("Insertando Numeraci�n ...");
   Pcabe.resetTexto();
   Pdatos.resetTexto();
   emp_codiE.requestFocus();
 }
 public boolean checkAddNew()
 {
   try {
     if (!emp_codiE.controla())
     {
       mensajeErr("Empresa NO valida");
       return false;
     }
   } catch (Exception k)
   {
     Error("Error al Controlar la empresa",k);
     return false;
   }
   if (eje_numeE.isNull())
   {
     mensajeErr("Ejercicio NO valido");
     eje_numeE.requestFocus();
     return false;
   }
   return true;
 }
 public void ej_addnew1(){
   try
   {
     s="SELECT * FROM v_numerac WHERE emp_codi = " +emp_codiE.getValorInt()+
         " AND eje_nume = "+eje_numeE.getValorInt();
     if (dtCon1.select(s))
     {
       mensajeErr("Registro de Numeracion YA existe");
       return;
     }
     dtAdd.addNew("v_numerac");
     dtAdd.setDato("emp_codi",emp_codiE.getValorInt());
     dtAdd.setDato("eje_nume",eje_numeE.getValorInt());

     actDatos(dtAdd);
     dtAdd.update(stUp);
     ctUp.commit();
     mensajeErr("Alta ... REALIZADA");
     mensaje("");
     activaTodo();
   } catch (Exception k)
   {
     Error("Error al Insertar Numeracion",k);
   }
    }

    void actDatos(DatosTabla dt) throws Exception
    {
        dt.setDato("num_seriea", num_serieaE.getValorDec());
        dt.setDato("num_serieb", num_seriebE.getValorDec());
        dt.setDato("num_seriec", num_seriecE.getValorDec());
        dt.setDato("num_seried", num_seriedE.getValorDec());
        dt.setDato("num_seriex", num_seriexE.getValorDec());
        dt.setDato("num_seriey", num_serieyE.getValorDec());

        dt.setDato("num_factur", num_facturE.getValorDec());
        dt.setDato("num_factub", num_factubE.getValorDec());
        dt.setDato("num_factuc", num_factucE.getValorDec());
        dt.setDato("num_factud", num_factudE.getValorDec());

        dt.setDato("num_secoma", num_secomaE.getValorDec());
        dt.setDato("num_secomb", num_secombE.getValorDec());
        dt.setDato("num_secomc", num_secomcE.getValorDec());
        dt.setDato("num_secomd", num_secomdE.getValorDec());
        dt.setDato("num_secomy", num_secomyE.getValorDec());

        dt.setDato("num_faccom", num_faccomE.getValorDec());
        dt.setDato("num_pedcom", num_pedcomE.getValorDec());

        dt.setDato("num_despi", num_despiE.getValorDec());
        dt.setDato("num_remesa", num_remesaE.getValorDec());    
    }
 public void canc_addnew(){
   mensaje("");
   mensajeErr("Cancelada Alta ...");
   verDatos();
   activaTodo();
 }

 public void PADDelete(){
     try
     {
       if (!setBloqueo(dtAdd, "v_numerac", emp_codiE.getValorInt()+"|"+eje_numeE.getValorDec()))
       {
         msgBox(msgBloqueo);
         nav.pulsado = navegador.NINGUNO;
         activaTodo();
         dtAdd.getConexion().rollback();
         return;
       }

       if (!dtAdd.select("SELECT * FROM v_numerac WHERE emp_codi = " +emp_codiE.getValorInt()+
           " AND eje_nume = "+eje_numeE.getValorInt(), true))
       {
         mensajeErr("Registro ha sido borrado");
         resetBloqueo(dtAdd,"v_numerac", emp_codiE.getValorInt()+"|"+eje_numeE.getValorDec());
         activaTodo();
         mensaje("");
         return;
       }

     }
     catch (Exception k)
     {
       Error("Error al bloquear el registro", k);
       return;
     }
     Baceptar.setEnabled(true);
     Bcancelar.setEnabled(true);
     Bcancelar.requestFocus();
     mensaje("Borrar registro activo ...");
 }

 public void ej_delete1(){
   try
     {
       dtAdd.delete(stUp);
       resetBloqueo(dtAdd,"v_numerac", emp_codiE.getValorInt()+"|"+eje_numeE.getValorDec());
       ctUp.commit();
       rgSelect();
     }
     catch (Exception ex)
     {
       Error("Error al borrar Registro",ex);
     }
     activaTodo();
     verDatos();
     mensaje("");
     mensajeErr("Registro ... Borrado");
 }

 public void canc_delete(){
   mensaje("");
   try
   {
     resetBloqueo(dtAdd, "v_numerac",
                  emp_codiE.getValorInt() + "|" + eje_numeE.getValorDec());

   }
   catch (Exception ex)
   {
     Error("Error al Quitar Bloqueo", ex);
     return;
   }
   mensajeErr("Modificacion de Datos Cancelada");
   activaTodo();
   verDatos();
 }


 public void activar(boolean b){
   emp_codiE.setEnabled(b);
   eje_numeE.setEnabled(b);
   num_serieaE.setEnabled(b);
   num_seriebE.setEnabled(b);
   num_seriecE.setEnabled(b);
   num_seriedE.setEnabled(b);
   num_seriexE.setEnabled(b);
   num_serieyE.setEnabled(b);
   num_facturE.setEnabled(b);
   num_factubE.setEnabled(b);
   num_factucE.setEnabled(b);
   num_factudE.setEnabled(b);
   
   num_secomdE.setEnabled(b);
   num_secombE.setEnabled(b);
   num_secomyE.setEnabled(b);
   num_secomcE.setEnabled(b);
   num_secomaE.setEnabled(b);
   num_faccomE.setEnabled(b);
   num_pedcomE.setEnabled(b);
   num_despiE.setEnabled(b);
   num_remesaE.setEnabled(b);
   Baceptar.setEnabled(b);
   Bcancelar.setEnabled(b);
 }
    void verDatos() {
        try {
            if (dtCons.getNOREG()) {
                return;
            }
            emp_codiE.setValorInt(dtCons.getInt("emp_codi"));
            eje_numeE.setText(dtCons.getString("eje_nume"));
            s = "SELECT * FROM v_numerac WHERE emp_codi = " + dtCons.getInt("emp_codi") +
                    " AND eje_nume = " + dtCons.getInt("eje_nume");
            if (!dtCon1.select(s)) {
                mensajeErr("Numeraci�n NO ENCONTRADA ... SEGURAMENTE SE BORRO");
                Pdatos.resetTexto();
                return;
            }
            num_serieaE.setValorDec(dtCon1.getDouble("num_seriea"));
            num_seriebE.setValorDec(dtCon1.getDouble("num_serieb"));
            num_seriecE.setValorDec(dtCon1.getDouble("num_seriec"));
            num_seriedE.setValorDec(dtCon1.getDouble("num_seried"));
            num_seriexE.setValorDec(dtCon1.getDouble("num_seriex"));
            num_serieyE.setValorDec(dtCon1.getDouble("num_seriey"));

            num_facturE.setValorInt(dtCon1.getInt("num_factur"));
            num_factubE.setValorInt(dtCon1.getInt("num_factub"));
            num_factucE.setValorInt(dtCon1.getInt("num_factuc"));
            num_factudE.setValorInt(dtCon1.getInt("num_factud"));
            
            num_secomdE.setValorDec(dtCon1.getDouble("num_secomd"));
            num_secombE.setValorDec(dtCon1.getDouble("num_secomb"));
            num_secomcE.setValorDec(dtCon1.getDouble("num_secomc"));
            num_secomaE.setValorDec(dtCon1.getDouble("num_secoma"));
            num_secomyE.setValorDec(dtCon1.getDouble("num_secomy"));
            num_faccomE.setValorDec(dtCon1.getDouble("num_faccom"));
            num_pedcomE.setValorDec(dtCon1.getDouble("num_pedcom"));
            num_despiE.setValorDec(dtCon1.getDouble("num_despi"));
            num_remesaE.setValorDec(dtCon1.getDouble("num_remesa"));

        } catch (Exception k) {
            Error("Error al ver Datos", k);
            return;
        }
    }

    @Override
  public void afterConecta() throws SQLException
  {
    emp_codiE.iniciar(dtStat, this, vl, EU);
    emp_codiE.setLabelEmp(emp_nombL);
  }
    @Override
  public void rgSelect() throws SQLException
   {
     super.rgSelect();
     if (!dtCons.getNOREG())
     {
       dtCons.last();
       nav.setEnabled(navegador.ULTIMO, false);
       nav.setEnabled(navegador.SIGUIENTE, false);
     }
     verDatos();
   }
     public static void llenaSeriesAlbVen(CComboBox serie) {
         llenaSeriesAlbVen(true,serie,true,false);
     }
     /**
      * Llena ComboBox con series de Albaran de Ventas disponibles
      * @param borrarItems Borrar los items existentes ?
      * @param serie ComboBox a llenar
      * @param incInterna Incluir Serie Alb. Interna (traspaso entre subEmpresas)
      * @param incTraAlm Incluir serie Traspaso entre albaranes
      */
    public static void llenaSeriesAlbVen(boolean borrarItems,CComboBox serie,boolean incInterna,boolean incTraAlm)
    {
        if (borrarItems)
           serie.removeAllItems();
        serie.addItem("A", "A");
        serie.addItem("B", "B");
        serie.addItem("C", "C");
        serie.addItem("D", "D");
        if (incInterna)
          serie.addItem("Y", "Y");
        if (incTraAlm)
          serie.addItem("X", "X");
    }
  public static void llenaSeriesFraVen(CComboBox serie) {
        serie.addItem("1", "1");
        serie.addItem("B", "B");
        serie.addItem("C", "C");
        serie.addItem("D", "D");
    }
    public static void llenaSeriesAlbCom(CComboBox serie) {
        llenaSeriesAlbVen(serie);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gnu.chu.controles.CButton Baceptar;
    private gnu.chu.controles.CButton Bcancelar;
    private gnu.chu.controles.CPanel PAlbCom;
    private gnu.chu.controles.CPanel PAlbVen;
    private gnu.chu.controles.CPanel PFraVen;
    private gnu.chu.controles.CPanel Pcabe;
    private gnu.chu.controles.CPanel Pdatos;
    private gnu.chu.controles.CPanel Pprinc;
    private gnu.chu.controles.CLabel cLabel1;
    private gnu.chu.controles.CLabel cLabel10;
    private gnu.chu.controles.CLabel cLabel11;
    private gnu.chu.controles.CLabel cLabel12;
    private gnu.chu.controles.CLabel cLabel15;
    private gnu.chu.controles.CLabel cLabel16;
    private gnu.chu.controles.CLabel cLabel17;
    private gnu.chu.controles.CLabel cLabel18;
    private gnu.chu.controles.CLabel cLabel19;
    private gnu.chu.controles.CLabel cLabel2;
    private gnu.chu.controles.CLabel cLabel20;
    private gnu.chu.controles.CLabel cLabel21;
    private gnu.chu.controles.CLabel cLabel22;
    private gnu.chu.controles.CLabel cLabel23;
    private gnu.chu.controles.CLabel cLabel3;
    private gnu.chu.controles.CLabel cLabel4;
    private gnu.chu.controles.CLabel cLabel5;
    private gnu.chu.controles.CLabel cLabel6;
    private gnu.chu.controles.CLabel cLabel7;
    private gnu.chu.controles.CLabel cLabel8;
    private gnu.chu.controles.CLabel cLabel9;
    private gnu.chu.controles.CTextField eje_numeE;
    private gnu.chu.camposdb.empPanel emp_codiE;
    private gnu.chu.controles.CLabel emp_nombL;
    private gnu.chu.controles.CTextField num_despiE;
    private gnu.chu.controles.CTextField num_faccomE;
    private gnu.chu.controles.CTextField num_factubE;
    private gnu.chu.controles.CTextField num_factucE;
    private gnu.chu.controles.CTextField num_factudE;
    private gnu.chu.controles.CTextField num_facturE;
    private gnu.chu.controles.CTextField num_pedcomE;
    private gnu.chu.controles.CTextField num_remesaE;
    private gnu.chu.controles.CTextField num_secomaE;
    private gnu.chu.controles.CTextField num_secombE;
    private gnu.chu.controles.CTextField num_secomcE;
    private gnu.chu.controles.CTextField num_secomdE;
    private gnu.chu.controles.CTextField num_secomyE;
    private gnu.chu.controles.CTextField num_serieaE;
    private gnu.chu.controles.CTextField num_seriebE;
    private gnu.chu.controles.CTextField num_seriecE;
    private gnu.chu.controles.CTextField num_seriedE;
    private gnu.chu.controles.CTextField num_seriexE;
    private gnu.chu.controles.CTextField num_serieyE;
    // End of variables declaration//GEN-END:variables

}
