/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gnu.chu.anjelica.almacen;


import gnu.chu.anjelica.pad.MantArticulos;
import gnu.chu.controles.Cgrid;
import gnu.chu.sql.DatosTabla;
import gnu.chu.utilidades.ventana;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JDialog;

/**
 *
 * @author cpuente
 */
public class IFIndivCaducidad
{    

    JDialog frame;
    ventana papa; 
    PIndivCaduc panel; 
    int swAceptado=CANCELAR;
    public final static int CANCELAR=0;
    public final static int ACEPTAR=1;
    Cgrid jt;
    /**
     * Creates new form IFStockPart
     * @param padre
     */
    public IFIndivCaducidad(ventana padre) {
         papa=padre;
         frame = new JDialog((Frame) null, true);
         
         frame.setSize(new Dimension(500, 400));
        
         frame.setTitle("Individuos con Caducidad");
       
//        this.getContentPane().add(statusBar, BorderLayout.SOUTH);
        
        //setVisibleCabeceraVentana(false);
        
        panel=new PIndivCaduc();
        panel.setMaximumSize(new Dimension(100,100));
        panel.setPreferredSize(new Dimension(100,100));
        activarEventos();
        frame.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);

        frame.getContentPane().add(panel,BorderLayout.CENTER);
        jt=panel.getGrid();
    }
    void activarEventos()
    {
        frame.addWindowListener(new WindowAdapter()
        {
            public void windowClosing(WindowEvent e) {
                swAceptado = CANCELAR;
                frame.setVisible(false);
            }
        });

        panel.getBotonAceptar().addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                    swAceptado=ACEPTAR;
                    matar();
            }
        });
        panel.getBotonCancelar().addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                matar();
            }
        });
    }
     public int getResultado()
    {
      return swAceptado;
     }
     void matar()
     {
      frame.setVisible(false);

     }
    public void iniciar(ArrayList<DatIndiv> listIndiv,DatosTabla dtStat) throws SQLException
    {

//        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
//        Dimension frameSize = frame.getSize();
//        if (frameSize.height > screenSize.height)
//          frameSize.height = screenSize.height;
//        if (frameSize.width > screenSize.width)
//          frameSize.width = screenSize.width;
        frame.setLocation((int)papa.getLocation().x+20, (int)papa.getLocation().y+80);
        swAceptado=CANCELAR;  
     
        jt.removeAllDatos();
        for (DatIndiv dtInd1 : listIndiv)
        {          
            ArrayList v=new ArrayList();
            v.add(dtInd1.getProducto()); // 0
            v.add(MantArticulos.getNombProd( dtInd1.getProducto(),dtStat)); // 1
            v.add(dtInd1.getEjercLot()); // 2
            v.add( dtInd1.getSerie()); // 3
            v.add(dtInd1.getLote()); //4
            v.add(dtInd1.getNumind()); // 5
            v.add(dtInd1.getCanti()); // 6
            v.add(dtInd1.getFechaCaducidad()); // 7
            jt.addLinea(v);
        }
        jt.requestFocusInicio();
        frame.setVisible(true);
//        mensajeErr("Datos individuos mostrados");
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
 
}
