/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gnu.chu.anjelica.almacen;

import gnu.chu.controles.StatusBar;
import gnu.chu.utilidades.ventana;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.beans.PropertyVetoException;
import java.sql.SQLException;
import java.sql.Types;
import java.util.ArrayList;

public class IFStockPart extends ventana
{
    ventana papa;
    /**
     * Creates new form IFStockPart
     * @param padre
     */
    public IFStockPart(ventana padre) {
         papa=padre;
         this.setTitle("Unidades disponibles");

        this.setVersion("2014-11-25");
        statusBar = new StatusBar(this);

        this.setPreferredSize(new Dimension(450, 302));
        this.setSize(new Dimension(450, 302));
        this.getContentPane().add(statusBar, BorderLayout.SOUTH);
        
        setVisibleCabeceraVentana(false);
        initComponents();
    }
    
    public void iniciar(int proCodi,String fecInv,String fecSaldo,ArrayList<DatIndiv> listIndiv) throws SQLException
    {
        if (!pro_codieE.isIniciado())
         pro_codieE.iniciar(papa.dtStat, papa, papa.vl, papa.EU);
        pro_codieE.setValorInt(proCodi,true);
        fecInvE.setText(fecInv);
        fecSaldoE.setText(fecSaldo);
        jt.removeAllDatos();
        for (DatIndiv dtInd1 : listIndiv)
        {
            if (dtInd1.getCanti()==0)
                continue;
            ArrayList v=new ArrayList();
            v.add(dtInd1.getEjercLot()); // 0
            v.add( dtInd1.getSerie()); // 1
            v.add(dtInd1.getLote()); //2
            v.add(dtInd1.getNumind()); // 3
            v.add(dtInd1.getCanti()); // 4
            v.add(dtInd1.getNumuni()); // 5
            jt.addLinea(v);
        }
        jt.requestFocusInicio();
        mensajeErr("Datos individuos mostrados");
    }
    
    @Override
    public void matar()
    {
      setVisible(false);

      papa.setEnabled(true);
      papa.setFoco(null);
      try {
          papa.setSelected(true);
      } catch (PropertyVetoException k){}
    }  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        cPanel1 = new gnu.chu.controles.CPanel();
        Pprinc = new gnu.chu.controles.CPanel();
        Pcabe = new gnu.chu.controles.CPanel();
        cLabel2 = new gnu.chu.controles.CLabel();
        fecInvE = new gnu.chu.controles.CTextField(Types.DATE,"dd-MM-yyyy");
        cLabel3 = new gnu.chu.controles.CLabel();
        fecSaldoE = new gnu.chu.controles.CTextField(Types.DATE,"dd-MM-yyyy");
        cLabel1 = new gnu.chu.controles.CLabel();
        pro_codieE = new gnu.chu.camposdb.proPanel();
        jt = new gnu.chu.controles.Cgrid(6);

        javax.swing.GroupLayout cPanel1Layout = new javax.swing.GroupLayout(cPanel1);
        cPanel1.setLayout(cPanel1Layout);
        cPanel1Layout.setHorizontalGroup(
            cPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        cPanel1Layout.setVerticalGroup(
            cPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Pprinc.setLayout(new java.awt.GridBagLayout());

        Pcabe.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        Pcabe.setMaximumSize(new java.awt.Dimension(401, 60));
        Pcabe.setMinimumSize(new java.awt.Dimension(401, 60));
        Pcabe.setPreferredSize(new java.awt.Dimension(401, 60));
        Pcabe.setQuery(true);
        Pcabe.setLayout(null);

        cLabel2.setText("Fecha Inv");
        Pcabe.add(cLabel2);
        cLabel2.setBounds(10, 5, 60, 17);

        fecInvE.setEditable(false);
        Pcabe.add(fecInvE);
        fecInvE.setBounds(70, 5, 80, 17);

        cLabel3.setText("Fecha Saldo");
        Pcabe.add(cLabel3);
        cLabel3.setBounds(190, 5, 70, 17);
        cLabel3.getAccessibleContext().setAccessibleName("Fecha Saldo");

        fecSaldoE.setEditable(false);
        Pcabe.add(fecSaldoE);
        fecSaldoE.setBounds(260, 5, 80, 17);

        cLabel1.setText("Producto ");
        Pcabe.add(cLabel1);
        cLabel1.setBounds(10, 30, 60, 15);

        pro_codieE.setEditable(false);
        Pcabe.add(pro_codieE);
        pro_codieE.setBounds(70, 30, 320, 17);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 0, 0);
        Pprinc.add(Pcabe, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        Pprinc.add(jt, gridBagConstraints);
        ArrayList v=new ArrayList();
        v.add("Ejer"); // 0
        v.add("Serie"); // 1
        v.add("Lote"); //2
        v.add("Ind"); // 3
        v.add("Kilos"); // 4
        v.add("Unid"); // 5
        jt.setCabecera(v);
        jt.setAnchoColumna(new int[]{40,30,50,40,50,40});
        jt.setAlinearColumna(new int[]{2,1,2,2,2,2});
        jt.setFormatoColumna(4, "---,--9.99");
        jt.setFormatoColumna(5, "###9");
        jt.setAjustarGrid(true);

        getContentPane().add(Pprinc, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gnu.chu.controles.CPanel Pcabe;
    private gnu.chu.controles.CPanel Pprinc;
    private gnu.chu.controles.CLabel cLabel1;
    private gnu.chu.controles.CLabel cLabel2;
    private gnu.chu.controles.CLabel cLabel3;
    private gnu.chu.controles.CPanel cPanel1;
    private gnu.chu.controles.CTextField fecInvE;
    private gnu.chu.controles.CTextField fecSaldoE;
    private gnu.chu.controles.Cgrid jt;
    private gnu.chu.camposdb.proPanel pro_codieE;
    // End of variables declaration//GEN-END:variables
}
