package gnu.chu.anjelica.almacen;
/**
 *
 * <p>Titulo: PIndivCaduc </p>
 * <p>Descripción: Panel para mostrar individuos con fecha caducidad problematica</p>
 *<p> Es utilizada en IFindivCaducidad</p>
 * <p>Copyright: Copyright (c) 2005-2018
 *  Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo
 *  los términos de la Licencia Pública General de GNU según es publicada por
 *  la Free Software Foundation, bien de la versión 2 de dicha Licencia
 *  o bien (según su elección) de cualquier versión posterior.
 *  Este programa se distribuye con la esperanza de que sea útil,
 *  pero SIN
 * NINGUNA GARANTIA, incluso sin la garantía MERCANTIL implícita
 *  o sin garantizar la CONVENIENCIA PARA UN PROPOSITO PARTICULAR.
 *  Véase la Licencia Pública General de GNU para más detalles.
 *  Debería haber recibido una copia de la Licencia Pública General junto con este programa.
 *  Si no ha sido así, escriba a la Free Software Foundation, Inc.,
 *  en 675 Mass Ave, Cambridge, MA 02139, EEUU.
 * </p>
 * @author chuchiP
 *
 */ 
import gnu.chu.controles.CButton;
import gnu.chu.controles.Cgrid;
import gnu.chu.utilidades.Iconos;
import java.util.ArrayList;


public class PIndivCaduc extends javax.swing.JPanel
{
    public PIndivCaduc() {
        initComponents();
    }
    public CButton getBotonAceptar()
    {
        return Baceptar;
    }
    public CButton getBotonCancelar()
    {
        return Bcancelar;
    }
    /**
     * Establece el mensaje de aviso 
     * @param msg 
     */
    public void setTextoAviso(String msg)
    {
        msgAvisoL.setText(msg);
    }
    public void setTextoAviso2(String msg)
    {
        msgAviso2L.setText(msg);
    }
    public Cgrid getGrid()
    {
        return jt;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jt = new gnu.chu.controles.Cgrid(9);
        Pconfir = new gnu.chu.controles.CPanel();
        msgAvisoL = new gnu.chu.controles.CLabel();
        Bcancelar = new gnu.chu.controles.CButton(Iconos.getImageIcon("cancel"));
        Baceptar = new gnu.chu.controles.CButton(Iconos.getImageIcon("check"));
        msgAviso2L = new gnu.chu.controles.CLabel();

        setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jt, gridBagConstraints);
        ArrayList v=new ArrayList();
        v.add("Producto"); // 0
        v.add("Nombre"); // 1
        v.add("Ejer"); // 2
        v.add("Serie"); // 3
        v.add("Lote"); //4
        v.add("Ind"); // 5
        v.add("Kilos"); // 6
        v.add("Fec.Cad"); // 7
        v.add("Incidencia"); // 7
        jt.setCabecera(v);
        jt.setAnchoColumna(new int[]{40,180,40,30,50,40,50,70,120});
        jt.setAlinearColumna(new int[]{2,0,2,1,2,2,2,1,0});
        jt.setFormatoColumna(6, "---,--9.99");

        jt.setAjustarGrid(true);

        Pconfir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Pconfir.setMaximumSize(new java.awt.Dimension(300, 60));
        Pconfir.setMinimumSize(new java.awt.Dimension(300, 60));
        Pconfir.setPreferredSize(new java.awt.Dimension(300, 60));
        Pconfir.setLayout(null);

        msgAvisoL.setBackground(java.awt.Color.orange);
        msgAvisoL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        msgAvisoL.setText("Articulos con Fecha Caducidad problematica");
        msgAvisoL.setOpaque(true);
        Pconfir.add(msgAvisoL);
        msgAvisoL.setBounds(10, 0, 280, 16);

        Bcancelar.setText("Cancelar");
        Pconfir.add(Bcancelar);
        Bcancelar.setBounds(170, 35, 100, 24);

        Baceptar.setText("Aceptar");
        Pconfir.add(Baceptar);
        Baceptar.setBounds(20, 35, 100, 24);

        msgAviso2L.setBackground(java.awt.Color.orange);
        msgAviso2L.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        msgAviso2L.setText("¿ Continuar ?");
        msgAviso2L.setOpaque(true);
        Pconfir.add(msgAviso2L);
        msgAviso2L.setBounds(80, 17, 110, 16);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        add(Pconfir, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gnu.chu.controles.CButton Baceptar;
    private gnu.chu.controles.CButton Bcancelar;
    private gnu.chu.controles.CPanel Pconfir;
    private gnu.chu.controles.Cgrid jt;
    private gnu.chu.controles.CLabel msgAviso2L;
    private gnu.chu.controles.CLabel msgAvisoL;
    // End of variables declaration//GEN-END:variables
}
