package gnu.chu.anjelica.almacen;

import gnu.chu.controles.CButton;
import gnu.chu.controles.Cgrid;
import gnu.chu.utilidades.Iconos;
import java.util.ArrayList;


public class PIndivCaduc extends javax.swing.JPanel
{

    /**
     * Creates new form PIndivCaduc
     */
    public PIndivCaduc() {
        initComponents();
    }
    public CButton getBotonAceptar()
    {
        return Baceptar;
    }
    public CButton getBotonCancelar()
    {
        return Bcancelar;
    }
    public Cgrid getGrid()
    {
        return jt;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jt = new gnu.chu.controles.Cgrid(8);
        Pconfir = new gnu.chu.controles.CPanel();
        msgAvisoL = new gnu.chu.controles.CLabel();
        Bcancelar = new gnu.chu.controles.CButton(Iconos.getImageIcon("cancel"));
        Baceptar = new gnu.chu.controles.CButton(Iconos.getImageIcon("check"));
        cLabel2 = new gnu.chu.controles.CLabel();

        setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jt, gridBagConstraints);
        ArrayList v=new ArrayList();
        v.add("Producto"); // 0
        v.add("Nombre"); // 1
        v.add("Ejer"); // 2
        v.add("Serie"); // 3
        v.add("Lote"); //4
        v.add("Ind"); // 5
        v.add("Kilos"); // 6
        v.add("Fec.Cad"); // 7
        jt.setCabecera(v);
        jt.setAnchoColumna(new int[]{40,180,40,30,50,40,50,70});
        jt.setAlinearColumna(new int[]{2,0,2,1,2,2,2,1});
        jt.setFormatoColumna(6, "---,--9.99");

        jt.setAjustarGrid(true);

        Pconfir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Pconfir.setMaximumSize(new java.awt.Dimension(300, 60));
        Pconfir.setMinimumSize(new java.awt.Dimension(300, 60));
        Pconfir.setPreferredSize(new java.awt.Dimension(300, 60));
        Pconfir.setLayout(null);

        msgAvisoL.setBackground(java.awt.Color.orange);
        msgAvisoL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        msgAvisoL.setText("Articulos con Fecha Caducidad problematica");
        msgAvisoL.setOpaque(true);
        Pconfir.add(msgAvisoL);
        msgAvisoL.setBounds(10, 0, 280, 16);

        Bcancelar.setText("Cancelar");
        Pconfir.add(Bcancelar);
        Bcancelar.setBounds(170, 35, 100, 24);

        Baceptar.setText("Aceptar");
        Pconfir.add(Baceptar);
        Baceptar.setBounds(20, 35, 100, 24);

        cLabel2.setBackground(java.awt.Color.orange);
        cLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cLabel2.setText("¿ Continuar ?");
        cLabel2.setOpaque(true);
        Pconfir.add(cLabel2);
        cLabel2.setBounds(80, 17, 110, 16);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        add(Pconfir, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gnu.chu.controles.CButton Baceptar;
    private gnu.chu.controles.CButton Bcancelar;
    private gnu.chu.controles.CPanel Pconfir;
    private gnu.chu.controles.CLabel cLabel2;
    private gnu.chu.controles.Cgrid jt;
    private gnu.chu.controles.CLabel msgAvisoL;
    // End of variables declaration//GEN-END:variables
}
