/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TransIndiv.java
 *
 * Created on 20-sep-2011, 13:32:15
 */
package gnu.chu.anjelica.almacen;

/**
 *
 * @author jpuente
 */
public class TransIndiv extends javax.swing.JInternalFrame {

    /** Creates new form TransIndiv */
    public TransIndiv() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pprinc = new gnu.chu.controles.CPanel();
        Pcabe = new gnu.chu.controles.CPanel();
        cLabel3 = new gnu.chu.controles.CLabel();
        pro_codiE = new gnu.chu.camposdb.proPanel();

        Pprinc.setLayout(null);

        Pcabe.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cLabel3.setText("Producto");

        javax.swing.GroupLayout PcabeLayout = new javax.swing.GroupLayout(Pcabe);
        Pcabe.setLayout(PcabeLayout);
        PcabeLayout.setHorizontalGroup(
            PcabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PcabeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(pro_codiE, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(148, Short.MAX_VALUE))
        );
        PcabeLayout.setVerticalGroup(
            PcabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PcabeLayout.createSequentialGroup()
                .addGroup(PcabeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pro_codiE, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        Pprinc.add(Pcabe);
        Pcabe.setBounds(20, 0, 570, 90);

        getContentPane().add(Pprinc, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gnu.chu.controles.CPanel Pcabe;
    private gnu.chu.controles.CPanel Pprinc;
    private gnu.chu.controles.CLabel cLabel3;
    private gnu.chu.camposdb.proPanel pro_codiE;
    // End of variables declaration//GEN-END:variables
}
