package gnu.chu.anjelica.ventas;
/**
 * <p>Titulo: PComClien</p>
 * <p>Descripcion: Panel de comentarios pedidos sobre clientes
* <p>Copyright: Copyright (c) 2005-2018
 *  Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo
 *  los terminos de la Licencia Pública General de GNU según es publicada por
 *  la Free Software Foundation, bien de la versión 2 de dicha Licencia
 *  o bien (según su elección) de cualquier versión posterior.
 *  Este programa se distribuye con la esperanza de que sea útil,
 *  pero SIN NINGUNA GARANTIA, incluso sin la garantía MERCANTIL implícita
 *  o sin garantizar la CONVENIENCIA PARA UN PROPOSITO PARTICULAR.
 *  Véase la Licencia Pública General de GNU para más detalles.
 *  Debería haber recibido una copia de la Licencia Pública General junto con este programa.
 *  Si no ha sido así, escriba a la Free Software Foundation, Inc.,
 *  en 675 Mass Ave, Cambridge, MA 02139, EEUU.
 * </p>
 * <p>Empresa: micasa</p>
 * @author chuchiP
 * @version 1.0
 */
import gnu.chu.controles.CPanel;
import gnu.chu.sql.DatosTabla;
import gnu.chu.utilidades.ventana;
import java.sql.SQLException;
import java.util.ArrayList;


public class PComClien extends CPanel
{
    DatosTabla dt;
    ventana padre;
    /**
     * Creates new form PComClien
     */
    public PComClien() {
        initComponents();
    }
    public void iniciar(DatosTabla dt,ventana papa) throws SQLException
    {
        this.dt=dt;
        padre=papa;             
    }
    
    public void mostrarComentarios(int cliCodi) throws SQLException
    {
      jtCom.removeAllDatos();
      String s="select * from v_cliente where cli_codi="+cliCodi;
      if (dt.select(s))
      {
          if (!dt.getString("cli_comped",true).equals(""))
          {
                 ArrayList v = new ArrayList();
                 v.add("");
                 v.add(dt.getString("cli_comped"));
                 jtCom.addLinea(v);
          }
      }
      if (!getSqlComent(dt, cliCodi))
          return;
      do
      {      
        ArrayList v = new ArrayList();
        v.add(dt.getFecha("cpv_fecha","dd-MM-yyyy"));
        v.add(dt.getString("cpv_come"));
        jtCom.addLinea(v);
      } while (dt.next());
      
    }
     boolean getSqlComent(DatosTabla dt, int cliCodi) throws SQLException
    {
       String s="SELECT * FROM compedven WHERE cli_codi = "+cliCodi+
        " ORDER BY cpv_fecha desc";
       return dt.select(s);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtCom = new gnu.chu.controles.Cgrid(2);

        setLayout(new java.awt.BorderLayout());

        ArrayList vCom=new ArrayList();
        vCom.add("Fecha");
        vCom.add("Comentario");
        jtCom.setCabecera(vCom);
        jtCom.setAlinearColumna(0,1);
        jtCom.setAnchoColumna(new int[]{63,407});
        jtCom.setAjustarGrid(true);
        jtCom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jtCom, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gnu.chu.controles.Cgrid jtCom;
    // End of variables declaration//GEN-END:variables
}
