package gnu.chu.anjelica.ventas;

/*
 *<p>Titulo: CLDepCli </p>
 * <p>Descripción: Consulta/Listado Depositos de clientes </p>
 * Este programa muestra el inventario en deposito tanto de un cliente como en total, en una fecha dada.
 * Permite sacar el genero entregado de una fecha a otra, asi como lo metido a deposito de una fecha a otra.
 * 
 *
 * <p>Copyright: Copyright (c) 2005-2016
 *  Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo
 *  los terminos de la Licencia Pública General de GNU según es publicada por
 *  la Free Software Foundation, bien de la versión 2 de dicha Licencia
 *  o bien (según su elección) de cualquier versión posterior.
 *  Este programa se distribuye con la esperanza de que sea útil,
 *  pero SIN NINGUNA GARANTIA, incluso sin la garantía MERCANTIL implícita
 *  o sin garantizar la CONVENIENCIA PARA UN PROPOSITO PARTICULAR.
 *  Véase la Licencia Pública General de GNU para más detalles.
 *  Debería haber recibido una copia de la Licencia Pública General junto con este programa.
 *  Si no ha sido así, escriba a la Free Software Foundation, Inc.,
 *  en 675 Mass Ave, Cambridge, MA 02139, EEUU.
 * </p>
 */
import gnu.chu.Menu.Principal;
import gnu.chu.controles.StatusBar;
import gnu.chu.utilidades.EntornoUsuario;
import gnu.chu.utilidades.Formatear;
import gnu.chu.utilidades.Iconos;
import gnu.chu.utilidades.ventana;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Types;
import java.util.ArrayList;
import java.util.HashMap;

public class CLDepCli extends ventana
{

     public CLDepCli(EntornoUsuario eu, Principal p) {
        this(eu, p, null);
    }

    public CLDepCli(EntornoUsuario eu, Principal p, HashMap<String,String> ht) {
        EU = eu;
        vl = p.panel1;
        jf = p;
        eje = true;

        try {
           
            setTitulo("Cons/List. Depositos de Clientes");
            if (jf.gestor.apuntar(this)) {
                jbInit();
            } else {
                setErrorInit(true);
            }
        } catch (Exception e) {
           ErrorInit(e);
        }
    }

    public CLDepCli(gnu.chu.anjelica.menu p, EntornoUsuario eu, HashMap <String,String> ht) {
        EU = eu;
        vl = p.getLayeredPane();
        eje = false;

        try {         
            setTitulo("Cons/List. Depositos de Clientes");
            jbInit();
        } catch (Exception e) {
           ErrorInit(e);
        }
    }
   
    private void jbInit() throws Exception {
        statusBar = new StatusBar(this);

        iniciarFrame();

        this.setVersion("2016-04-28");

        initComponents();
        this.setSize(new Dimension(730, 535));
        this.getContentPane().add(statusBar, BorderLayout.SOUTH);

        conecta();
    }

    @Override
    public void iniciarVentana() throws Exception 
    {
        fechaE.setDate(Formatear.getDateAct());
        cli_codiE.iniciar(dtStat, this, vl, EU);
        activarEventos();
    }
    
    void activarEventos()
    {
      Baceptar.addActionListener(new ActionListener(){
       @Override
       public void actionPerformed(ActionEvent e){
          // verDatos();
       } 
      });
      tipoConsC.addActionListener(new ActionListener(){
       @Override
       public void actionPerformed(ActionEvent e){
           fecfinE.setEnabled(! tipoConsC.getValor().equals("I"));
       } 
      });
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pprinc = new gnu.chu.controles.CPanel();
        PCabe = new gnu.chu.controles.CPanel();
        cLabel6 = new gnu.chu.controles.CLabel();
        fechaE = new gnu.chu.controles.CTextField(Types.DATE,"dd-MM-yyyy");
        cLabel10 = new gnu.chu.controles.CLabel();
        cli_codiE = new gnu.chu.camposdb.cliPanel();
        cLabel1 = new gnu.chu.controles.CLabel();
        tipoConsC = new gnu.chu.controles.CComboBox();
        Baceptar = new gnu.chu.controles.CButton(Iconos.getImageIcon("check"));
        cLabel7 = new gnu.chu.controles.CLabel();
        fecfinE = new gnu.chu.controles.CTextField(Types.DATE,"dd-MM-yyyy");
        jt = new gnu.chu.controles.Cgrid(7);
        PPie = new gnu.chu.controles.CPanel();

        Pprinc.setLayout(null);

        PCabe.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PCabe.setLayout(null);

        cLabel6.setText("De Fecha");
        PCabe.add(cLabel6);
        cLabel6.setBounds(0, 2, 60, 18);
        PCabe.add(fechaE);
        fechaE.setBounds(70, 2, 76, 18);

        cLabel10.setText("De Cliente");
        PCabe.add(cLabel10);
        cLabel10.setBounds(5, 26, 65, 18);
        PCabe.add(cli_codiE);
        cli_codiE.setBounds(70, 26, 360, 18);

        cLabel1.setText("Tipo");
        PCabe.add(cLabel1);
        cLabel1.setBounds(310, 2, 40, 17);

        tipoConsC.addItem("Inventario","I");
        tipoConsC.addItem("Salidas","S");
        tipoConsC.addItem("Entradas","E");
        tipoConsC.addItem("Movimientos","M");
        PCabe.add(tipoConsC);
        tipoConsC.setBounds(360, 2, 120, 17);

        Baceptar.setText("Aceptar");
        PCabe.add(Baceptar);
        Baceptar.setBounds(440, 22, 100, 24);

        cLabel7.setText("A Fecha");
        PCabe.add(cLabel7);
        cLabel7.setBounds(160, 2, 50, 17);
        PCabe.add(fecfinE);
        fecfinE.setBounds(210, 2, 76, 17);

        Pprinc.add(PCabe);
        PCabe.setBounds(0, 0, 550, 50);

        ArrayList v=new ArrayList();
        v.add("Fecha"); // 0
        v.add("E/S"); // 1
        v.add("Articulo"); // 2
        v.add("Descrip."); // 3
        v.add("Individuo"); // 4
        v.add("Unid"); // 5
        v.add("Kilos"); // 6
        jt.setCabecera(v);
        jt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Pprinc.add(jt);
        jt.setBounds(0, 60, 550, 170);

        PPie.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        PPie.setLayout(null);
        Pprinc.add(PPie);
        PPie.setBounds(0, 240, 550, 40);

        getContentPane().add(Pprinc, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gnu.chu.controles.CButton Baceptar;
    private gnu.chu.controles.CPanel PCabe;
    private gnu.chu.controles.CPanel PPie;
    private gnu.chu.controles.CPanel Pprinc;
    private gnu.chu.controles.CLabel cLabel1;
    private gnu.chu.controles.CLabel cLabel10;
    private gnu.chu.controles.CLabel cLabel6;
    private gnu.chu.controles.CLabel cLabel7;
    private gnu.chu.camposdb.cliPanel cli_codiE;
    private gnu.chu.controles.CTextField fecfinE;
    private gnu.chu.controles.CTextField fechaE;
    private gnu.chu.controles.Cgrid jt;
    private gnu.chu.controles.CComboBox tipoConsC;
    // End of variables declaration//GEN-END:variables
}
