package gnu.chu.anjelica.ventas;

import gnu.chu.controles.CPanel;
import gnu.chu.sql.DatosTabla;
import gnu.chu.utilidades.ventana;
import gnu.chu.utilidades.ventanaPad;
import java.sql.SQLException;
import java.sql.Types;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * <p>Titulo: pstockAct </p>
 * <p>Descripción: Panel Stock Actual. Muestra el stock actual y previsible de los productos
 * en un almacen o en todos. Permite ver el total de kilos por producto y desglosandolo por
 * proveedor y fecha caducidad </p>
* <p>Copyright: Copyright (c) 2005-2016
 *  Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo
 *  los terminos de la Licencia Pública General de GNU seg�n es publicada por
 *  la Free Software Foundation, bien de la versión 2 de dicha Licencia
 *  o bien (según su elección) de cualquier versión posterior.
 *  Este programa se distribuye con la esperanza de que sea útil,
 *  pero SIN NINGUNA GARANTIA, incluso sin la garantía MERCANTIL implícita
 *  o sin garantizar la CONVENIENCIA PARA UN PROPOSITO PARTICULAR.
 *  Véase la Licencia Pública General de GNU para más detalles.
 *  Debería haber recibido una copia de la Licencia Pública General junto con este programa.
 *  Si no ha sido así, escriba a la Free Software Foundation, Inc.,
 *  en 675 Mass Ave, Cambridge, MA 02139, EEUU.
 * </p>
 * @author chuchiP
 * @version 1.0
 *
 */
public class PConfPedVen extends CPanel
{   
    ventanaPad papa;
    int empCodi,pvcAno;    
    int pvcNume,pvlNumlin;
    DatosTabla dtAdd;
    
    public PConfPedVen() {
       
        initComponents();
    }
    
    void iniciar(ventanaPad padre)
    {
        this.papa=padre;       
        dtAdd=papa.dtAdd;
    }
    
   /**
    * Establece el pedido sobre el que se trabajara
    * @param empresa
    * @param ejercicio
    * @param pedido 
    */
    public void setPedido(int empresa,int ejercicio,int pedido)
    {
       this.empCodi=empresa;
       this.pvcAno=ejercicio;
       this.pvcNume=pedido;
    }
    /**
     * Establece la linea del pedido. Actualiza los TextFields
     * @param lineaPedido 
     */
    public void setLineaPedido(int lineaPedido)
    {
        try
        {
            pvlNumlin=lineaPedido;
            if (!buscaModPed(empCodi,pvcAno,pvcNume,pvlNumlin,false))
            {
                resetTexto();
                return;
            }
            pvm_cantiE.setValorDec(dtAdd.getDouble("pvm_canti"));
            usu_nombE.setText(dtAdd.getString("usu_nomb"));
            pvm_fechaE.setText(dtAdd.getFecha("pvm_fecha", "dd-MM-yyyy hh:mm"));
        } catch (SQLException ex)
        {
            papa.Error("Error al buscar Modficacion de Pedido", ex);
        }
    }
   
    public void resetTexto()
    {
        if (pvm_cantiE==null)
            return;
        pvm_cantiE.resetTexto();
        pvm_fechaE.resetTexto();
        usu_nombE.resetTexto();
    }

    private boolean buscaModPed(int empCodi,int pvcAno,int pvcNume,int pvlNumlin,boolean update) throws SQLException
    {
        if (papa==null)
            return false;
        if (papa.muerto )
            return false;
        String s= "select * from pedvenmod as p "+
            " where emp_codi ="+empCodi+
            " and eje_nume = " + pvcAno +
            " and pvc_nume = " + pvcNume+
            " and pvl_numlin= "+pvlNumlin;
        return dtAdd.select(s,update);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cLabel1 = new gnu.chu.controles.CLabel();
        pvm_cantiE = new gnu.chu.controles.CTextField(Types.DECIMAL,"##9");
        cLabel2 = new gnu.chu.controles.CLabel();
        usu_nombE = new gnu.chu.controles.CTextField();
        cLabel3 = new gnu.chu.controles.CLabel();
        pvm_fechaE = new gnu.chu.controles.CTextField();

        setLayout(null);

        cLabel1.setText("Fecha");
        add(cLabel1);
        cLabel1.setBounds(360, 2, 40, 17);

        pvm_cantiE.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pvm_cantiEFocusLost(evt);
            }
        });
        add(pvm_cantiE);
        pvm_cantiE.setBounds(120, 2, 50, 17);

        cLabel2.setText("Cantidad Preparada");
        add(cLabel2);
        cLabel2.setBounds(2, 2, 120, 17);

        usu_nombE.setEnabled(false);
        add(usu_nombE);
        usu_nombE.setBounds(240, 2, 100, 17);

        cLabel3.setText("Usuario");
        add(cLabel3);
        cLabel3.setBounds(190, 2, 50, 17);

        pvm_fechaE.setEnabled(false);
        add(pvm_fechaE);
        pvm_fechaE.setBounds(410, 2, 120, 17);
    }// </editor-fold>//GEN-END:initComponents

    private void pvm_cantiEFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pvm_cantiEFocusLost
        try
        {
            if (pvcAno==0 || pvlNumlin==0)
                return;
            boolean swExi=buscaModPed(empCodi,pvcAno,pvcNume,pvlNumlin,true);
            
            
            if (! swExi && pvm_cantiE.getValorDec()==0)
                    return;
            if (!swExi)
            {
                dtAdd.addNew();
                dtAdd.setDato("emp_codi",empCodi);
                dtAdd.setDato("eje_nume",pvcAno);
                dtAdd.setDato("pvc_nume",pvcNume);
                dtAdd.setDato("pvl_numlin",pvlNumlin);
            }
            else
            {
                if (pvm_cantiE.getValorDec()==dtAdd.getDouble("pvm_canti"))
                {
                    dtAdd.commit();
                    return;
                }
                dtAdd.edit();
            }
            dtAdd.setDato("pvm_canti",pvm_cantiE.getValorDec());
            dtAdd.setDato("usu_nomb",papa.EU.usuario);
            dtAdd.setDato("pvm_fecha","current_timestamp");
            dtAdd.update();
            papa.mensajeRapido("Actualizada Cantidad preparada en pedido ");
            dtAdd.commit();
            actualCanti(pvm_cantiE.getValorDec());
        } catch (SQLException ex)
        {
           papa.Error("Error al actualizar de Pedido", ex);
        }
    }//GEN-LAST:event_pvm_cantiEFocusLost
    /**
     * Funcion a machacar para hacer algo cuando se actualize la cantidad
     * @param cantidad 
     */
    public void actualCanti(double cantidad)
    {
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gnu.chu.controles.CLabel cLabel1;
    private gnu.chu.controles.CLabel cLabel2;
    private gnu.chu.controles.CLabel cLabel3;
    private gnu.chu.controles.CTextField pvm_cantiE;
    private gnu.chu.controles.CTextField pvm_fechaE;
    private gnu.chu.controles.CTextField usu_nombE;
    // End of variables declaration//GEN-END:variables
}
