
package gnu.chu.anjelica.tiempos;

import gnu.chu.controles.CPanel;
import gnu.chu.sql.DatosTabla;
import java.sql.SQLException;
import java.sql.Types;
import java.util.ArrayList;

public class PTiempoPedido extends  CPanel
    
{

    public PTiempoPedido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cam_codiE = new gnu.chu.controles.CTextField(Types.CHAR,"X",2);
        usu_nombE = new gnu.chu.controles.CTextField(Types.CHAR,"X",15);
        tit_tipoE = new gnu.chu.controles.CTextField(Types.CHAR,"X",1);
        tit_tiempoE = new gnu.chu.controles.CTextField(Types.DECIMAL,"##9");
        jt = new gnu.chu.controles.CGridEditable();
        Presumen = new gnu.chu.controles.CPanel();
        tiempoL = new gnu.chu.controles.CLabel();
        tiempoE = new gnu.chu.controles.CTextField(Types.DECIMAL,"##9");

        cam_codiE.setMayusc(true);

        usu_nombE.setMinusc(true);

        tit_tipoE.setMayusc(true);

        setLayout(null);

        ArrayList v= new ArrayList();
        v.add("Camara");
        v.add("Operario");
        v.add("Tipo");
        v.add("Tiempo");
        jt.setCabecera(v);
        ArrayList vc=new ArrayList();
        vc.add(cam_codiE);
        vc.add(usu_nombE);
        vc.add(tit_tipoE);
        vc.add(tit_tiempoE);
        jt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jt);
        jt.setBounds(3, 1, 370, 110);

        Presumen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Presumen.setLayout(null);

        tiempoL.setText("Minutos Totales");
        Presumen.add(tiempoL);
        tiempoL.setBounds(10, 5, 100, 17);
        Presumen.add(tiempoE);
        tiempoE.setBounds(110, 5, 40, 17);

        add(Presumen);
        Presumen.setBounds(80, 110, 190, 30);
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Muestra los datos del pedido mandado por pantalla.
     * @param titId
     * @param dt
     * @throws SQLException 
     */
    public void setPedido(int titId,DatosTabla dt) throws SQLException
    {
        String s="select cam_codi,usu_nomb,tit_tipo,tit_tiempo from v_tiempospedido where tit_id= "+titId+" order by cam_codi";
        jt.setEnabled(false);
        resetTexto();
        if (dt.select(s))
        {
            int tiempo=0;
            do
            {
                ArrayList v=new ArrayList();
                v.add(dt.getString("cam_codi"));
                v.add(dt.getString("usu_nomb"));
                v.add(dt.getString("tit_tipo"));
                v.add(dt.getInt("tit_tiempo"));
                tiempo+=dt.getInt("tit_tiempo");
            } while (dt.next());
            tiempoE.setValorInt(tiempo);
        }
    }
    public void setEnabledGrid(boolean enable)
    {
        jt.setEnabled(enable);
    }
    @Override
    public void resetTexto()
    {
        jt.removeAllDatos();
        tiempoE.resetTexto();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gnu.chu.controles.CPanel Presumen;
    private gnu.chu.controles.CTextField cam_codiE;
    private gnu.chu.controles.CGridEditable jt;
    private gnu.chu.controles.CTextField tiempoE;
    private gnu.chu.controles.CLabel tiempoL;
    private gnu.chu.controles.CTextField tit_tiempoE;
    private gnu.chu.controles.CTextField tit_tipoE;
    private gnu.chu.controles.CTextField usu_nombE;
    // End of variables declaration//GEN-END:variables
}
