package gnu.chu.anjelica.sql;
// Generated 26-oct-2011 10:11:38 by Hibernate Tools 3.2.1.GA



/**
 * DesporigId generated by hbm2java
 */
public class DesporigId  implements java.io.Serializable {


     private int ejeNume;
     private int deoCodi;

    public DesporigId() {
    }

    public DesporigId(int ejeNume, int deoCodi) {
       this.ejeNume = ejeNume;
       this.deoCodi = deoCodi;
    }
   
    public int getEjeNume() {
        return this.ejeNume;
    }
    
    public void setEjeNume(int ejeNume) {
        this.ejeNume = ejeNume;
    }
    public int getDeoCodi() {
        return this.deoCodi;
    }
    
    public void setDeoCodi(int deoCodi) {
        this.deoCodi = deoCodi;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DesporigId) ) return false;
		 DesporigId castOther = ( DesporigId ) other; 
         
		 return (this.getEjeNume()==castOther.getEjeNume())
 && (this.getDeoCodi()==castOther.getDeoCodi());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getEjeNume();
         result = 37 * result + this.getDeoCodi();
         return result;
   }   


}


